/**
 * TYPEFLOW — Duolingo-Grade Gamification Data Engine
 * Units, Lessons, Leagues, Quests, Achievements, and Shop Catalog.
 * Fully planned comprehensive curriculum with extended texts, multi-stage progression,
 * challenging quests & achievements, and strict gem economy.
 */

import { Unit, Lesson, LessonStage, DailyQuest, Achievement, ShopItem, LeagueMember, LeagueTier, TechAd } from './types';
import { Locale } from '@/dictionaries';

// ─── 1. DAKTİLO AKADEMİSİ: 10 KAPSAMLI ÜNİTE VE 50+ DERS (TÜRKÇE) ─────────────
export const ACADEMY_UNITS_TR: Unit[] = [
  {
    id: 1,
    title: 'Ünite 1: Ev Sırası Temelleri (Home Row)',
    description: 'Sol ve sağ elin ana yerleşimi: A, S, D, F ve J, K, L, Ş tuşları. Temel kılavuz ve parmak disiplini.',
    themeColor: '#3b82f6',
    lessons: [
      {
        id: 'u1-l1',
        unitId: 1,
        title: 'Kılavuz Tuşlar: F ve J',
        description: 'İşaret parmaklarını klavyedeki kabartmalı kılavuz tuşlarına alıştır ve ritmik vuruşlar yap.',
        icon: '☝️',
        targetChars: ['f', 'j', ' '],
        words: [
          'f', 'j', 'ff', 'jj', 'fj', 'jf', 'fjf', 'jfj', 'fjjf', 'jffj',
          'fff', 'jjj', 'fjfj', 'jfjf', 'fjj', 'jff', 'jfjfj', 'fjfjf', 'ffjj', 'jjff',
          'f', 'j', 'ff', 'jj', 'jf', 'fj', 'fjf', 'jfj', 'ffj', 'jjf',
          'fjfj', 'jfjf', 'fjjf', 'jffj', 'fff', 'jjj', 'fj', 'jf', 'f', 'j'
        ],
        stars: 0,
        status: 'active',
        minWpm: 18,
        minAccuracy: 92,
        xpReward: 25,
        gemReward: 2,
      },
      {
        id: 'u1-l2',
        unitId: 1,
        title: 'Sol El Ev Sırası: A, S, D, F',
        description: 'Sol el parmaklarını (serçe, yüzük, orta, işaret) ev sırasına yerleştir ve kombine kelimeler üret.',
        icon: '👈',
        targetChars: ['a', 's', 'd', 'f'],
        words: [
          'as', 'da', 'fa', 'sad', 'saf', 'ada', 'fas', 'safahat', 'kasa', 'fasa',
          'ada', 'asa', 'dada', 'fafa', 'sasa', 'saf', 'asaf', 'faal', 'sada', 'feda',
          'af', 'saf', 'fas', 'ada', 'kasa', 'sadakat', 'safra', 'adası', 'safha', 'fasa',
          'asla', 'safa', 'dafa', 'adad', 'sasa', 'fafa', 'asaf', 'sadık', 'sada', 'afal'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 20,
        minAccuracy: 92,
        xpReward: 30,
        gemReward: 2,
      },
      {
        id: 'u1-l3',
        unitId: 1,
        title: 'Sağ El Ev Sırası: J, K, L, Ş',
        description: 'Sağ el parmaklarının ev sırası koordinasyonu ve Türkçe klavyenin Ş tuşu uzanımı.',
        icon: '👉',
        targetChars: ['j', 'k', 'l', 'ş'],
        words: [
          'ka', 'al', 'aş', 'kaş', 'şal', 'ala', 'kala', 'şaka', 'şafak', 'kasa',
          'kal', 'kaş', 'şal', 'kıl', 'kaşık', 'alkış', 'kalkan', 'şalak', 'kallavi', 'şaka',
          'al', 'kal', 'şal', 'şaka', 'kaş', 'aş', 'kala', 'şafak', 'kakaş', 'şalka',
          'kalk', 'şalvar', 'akşam', 'kaşla', 'şafak', 'kalafat', 'aşlık', 'şah', 'kallavi', 'şaş'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 22,
        minAccuracy: 92,
        xpReward: 30,
        gemReward: 2,
      },
      {
        id: 'u1-l4',
        unitId: 1,
        title: 'İki El Ev Sırası Dengesi',
        description: 'Sol ve sağ el parmaklarını nöbetleşe kullanarak dengeli ritim geliştir.',
        icon: '⚖️',
        targetChars: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ş'],
        words: [
          'kasa', 'şafak', 'sakal', 'fakat', 'salata', 'dalaş', 'kafa', 'fal', 'kalas', 'dalga',
          'kasa', 'saf', 'şaka', 'faka', 'sada', 'kala', 'şafak', 'dalaş', 'kafa', 'salata',
          'fakat', 'sakal', 'şal', 'dal', 'kal', 'fal', 'kasa', 'ada', 'şaka', 'safahat',
          'kallavi', 'dalaş', 'salak', 'şafak', 'faka', 'sada', 'kafa', 'sakal', 'fakat', 'kasa'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 25,
        minAccuracy: 93,
        xpReward: 35,
        gemReward: 3,
      },
      {
        id: 'u1-l5',
        unitId: 1,
        title: 'Ev Sırası Cümle Akışı',
        description: 'Yalnızca ev sırasındaki harflerden oluşan anlamlı ve ritmik cümleler yaz.',
        icon: '📜',
        targetChars: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ş'],
        words: [
          'kasa', 'sağlam', 'fakat', 'şafak', 'söktü', 'kala', 'kaldı', 'şaka', 'faka', 'bastı',
          'salata', 'kasa', 'sakal', 'şafak', 'dalaş', 'kafa', 'fakat', 'kalas', 'safahat', 'dal',
          'ada', 'kasa', 'şaka', 'fakat', 'sakal', 'şafak', 'salata', 'dalaş', 'kafa', 'kallavi',
          'fal', 'kal', 'şal', 'kasa', 'fakat', 'şafak', 'sada', 'kala', 'şaka', 'saf'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 26,
        minAccuracy: 94,
        xpReward: 40,
        gemReward: 3,
      },
      {
        id: 'u1-l6',
        unitId: 1,
        title: 'Ev Sırası Ustalık Sınavı',
        description: 'Ev sırasını hiç klavyeye bakmadan tam doğrulukla ve seri vuruşlarla tamamla.',
        icon: '🏆',
        targetChars: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ş'],
        words: [
          'şafak', 'sökerken', 'kasa', 'sağlam', 'fakat', 'dalaş', 'başladı', 'sakal', 'salata',
          'kafa', 'şaka', 'faka', 'bastı', 'kallavi', 'kalas', 'safahat', 'şafak', 'sakal', 'fakat',
          'dalaş', 'salata', 'kasa', 'kafa', 'fal', 'kal', 'şal', 'ada', 'şaka', 'safahat',
          'kasa', 'şafak', 'fakat', 'sakal', 'dalaş', 'salata', 'kafa', 'kallavi', 'şaka', 'sağlam'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 95,
        xpReward: 50,
        gemReward: 5,
      },
    ],
  },
  {
    id: 2,
    title: 'Ünite 2: Üst Sıra Parmak Açılımları',
    description: 'Yukarı uzanma egzersizleri: E, R, T, Y, U, I, O, P, Ğ ve Ü tuşları ile zengin kelimeler.',
    themeColor: '#10b981',
    lessons: [
      {
        id: 'u2-l1',
        unitId: 2,
        title: 'Merkez Üst Sıra: E ve R Tuşları',
        description: 'Türkçede en yüksek sıklıkta geçen sesli ve sessiz harf kombinasyonuna hakim ol.',
        icon: '⚡',
        targetChars: ['e', 'r'],
        words: [
          'er', 're', 'ere', 'ser', 'der', 'fer', 'eser', 'fare', 'kale', 'sefer',
          'dere', 'kare', 'file', 'sere', 'terek', 'erken', 'rehber', 'esef', 'fener', 'keser',
          'er', 'ser', 'der', 'eser', 'fare', 'kale', 'sefer', 'dere', 'kare', 'erken',
          'rehber', 'fener', 'keser', 'terek', 'esef', 'sergi', 'dergi', 'sefer', 'resmi', 'derin'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 24,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 2,
      },
      {
        id: 'u2-l2',
        unitId: 2,
        title: 'Merkez Üst Sıra: T ve Y Tuşları',
        description: 'İşaret parmaklarının üst merkez uzanımları: T ve Y koordinasyonu.',
        icon: '🎯',
        targetChars: ['t', 'y'],
        words: [
          'at', 'ay', 'yata', 'tasa', 'tava', 'taya', 'tayfa', 'telsiz', 'tarih', 'yatak',
          'yetki', 'takat', 'yatsı', 'yazar', 'tatar', 'tayin', 'yayık', 'teyze', 'yetim', 'teyp',
          'tarih', 'tayfa', 'yatak', 'yetki', 'telsiz', 'yazar', 'tayın', 'teyze', 'tava', 'tasa',
          'yolcu', 'tutar', 'yayın', 'taktik', 'yalan', 'tarak', 'yatay', 'tebrik', 'yeter', 'tören'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 25,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 2,
      },
      {
        id: 'u2-l3',
        unitId: 2,
        title: 'Sağ Üst Sıra: U, I, O, P Tuşları',
        description: 'Sağ el parmaklarının üst sıradaki sesli harfler ve P tuşu esnekliği.',
        icon: '🖐️',
        targetChars: ['u', 'ı', 'o', 'p'],
        words: [
          'ot', 'pul', 'oluş', 'posta', 'pilot', 'toprak', 'pazar', 'patika', 'portakal', 'pusula',
          'pota', 'oluk', 'piliç', 'ortak', 'polis', 'pudra', 'operatör', 'otopark', 'prens', 'palto',
          'toprak', 'posta', 'patika', 'pilot', 'pazar', 'portakal', 'pusula', 'ortak', 'polis', 'operatör',
          'palto', 'pota', 'oluk', 'pul', 'oluş', 'otopark', 'pudra', 'prens', 'posta', 'patika'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 27,
        minAccuracy: 93,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u2-l4',
        unitId: 2,
        title: 'Türkçe Özel Üst Tuşlar: Ğ ve Ü',
        description: 'Türkçe klavyenin sağ üst kenar tuşları olan Ğ ve Ü harflerinde serçe parmak ustalığı.',
        icon: '🇹🇷',
        targetChars: ['ğ', 'ü'],
        words: [
          'dağ', 'bağ', 'sağ', 'öğle', 'ümit', 'üretim', 'ülke', 'üçüncü', 'doğru', 'ağaç',
          'çağdaş', 'öğrenci', 'yağmur', 'eğitim', 'sağlık', 'düğün', 'göğüs', 'öğretmen', 'üstat', 'bağlantı',
          'doğru', 'üretim', 'sağlık', 'eğitim', 'yağmur', 'öğrenci', 'üçüncü', 'çağdaş', 'ağaç', 'ümit',
          'dağ', 'bağ', 'sağ', 'düğün', 'üstat', 'bağlantı', 'göğüs', 'öğle', 'öğretmen', 'ülke'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 93,
        xpReward: 40,
        gemReward: 3,
      },
      {
        id: 'u2-l5',
        unitId: 2,
        title: 'Sol Üst Sıra: Q ve W Tuşları',
        description: 'Yabancı kökenli terimler, internet adresleri ve yazılım komutları için Q ve W açılımları.',
        icon: '🌐',
        targetChars: ['q', 'w'],
        words: [
          'web', 'webmaster', 'query', 'queue', 'quick', 'wifi', 'switch', 'view', 'workflow', 'gateway',
          'quality', 'network', 'powershell', 'window', 'hardware', 'software', 'download', 'upload', 'password', 'keyword',
          'web', 'query', 'queue', 'quick', 'wifi', 'switch', 'workflow', 'gateway', 'network', 'window',
          'software', 'hardware', 'download', 'upload', 'password', 'keyword', 'view', 'powershell', 'webmaster', 'quality'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 30,
        minAccuracy: 93,
        xpReward: 45,
        gemReward: 3,
      },
      {
        id: 'u2-l6',
        unitId: 2,
        title: 'Üst Sıra Ustalık Sınavı',
        description: 'Ev sırası ve üst sıranın tamamını harmanlayan yoğun kelime ve cümle maratonu.',
        icon: '🌟',
        targetChars: ['e', 'r', 't', 'y', 'u', 'ı', 'o', 'p', 'ğ', 'ü'],
        words: [
          'operatör', 'portakal', 'tasarım', 'yetenek', 'tarihi', 'telefon', 'öğretmen', 'yağmur', 'üretim', 'eğitim',
          'pusula', 'toprak', 'rehber', 'fener', 'sefer', 'yolcu', 'taktik', 'doğruluk', 'üçüncü', 'sağlıklı',
          'tasarımcı', 'yetenekli', 'operatörler', 'eğitimli', 'öğrenciler', 'portakallar', 'tarihçiler', 'pusulalar', 'yolcular', 'telefonlar',
          'rehberlik', 'fenerler', 'seferler', 'üreticiler', 'sağlam', 'doğru', 'üstatlar', 'bağlantılar', 'taktikler', 'topraklar'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 32,
        minAccuracy: 95,
        xpReward: 55,
        gemReward: 6,
      },
    ],
  },
  {
    id: 3,
    title: 'Ünite 3: Alt Sıra ve Türkçe Karakterler',
    description: 'Aşağı uzanmalar: Z, X, C, V, B, N, M, Ö, Ç tuşları ile tam klavye geometrisi.',
    themeColor: '#8b5cf6',
    lessons: [
      {
        id: 'u3-l1',
        unitId: 3,
        title: 'Sol Alt Sıra: Z, X, C Tuşları',
        description: 'Sol elin serçe, yüzük ve orta parmak aşağı uzanımları.',
        icon: '⚓',
        targetChars: ['z', 'x', 'c'],
        words: [
          'can', 'cevap', 'cam', 'cuma', 'zar', 'zil', 'zaman', 'zincir', 'zemin', 'ceza',
          'cihaz', 'cesur', 'ciddi', 'ziyaret', 'zirve', 'zengin', 'cüzdan', 'cümle', 'coşku', 'cazip',
          'zaman', 'cevap', 'zincir', 'cihaz', 'zirve', 'zengin', 'cümle', 'cesur', 'ciddi', 'ziyaret',
          'cam', 'zar', 'zil', 'cuma', 'ceza', 'zemin', 'cüzdan', 'coşku', 'cazip', 'cihaz'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 27,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 2,
      },
      {
        id: 'u3-l2',
        unitId: 3,
        title: 'Merkez Alt Sıra: V ve B Tuşları',
        description: 'İşaret parmaklarının alt merkez uzanımları: V ve B dinamikleri.',
        icon: '🌊',
        targetChars: ['v', 'b'],
        words: [
          've', 'bu', 'var', 'bana', 'bavul', 'vicdan', 'bakış', 'vatan', 'bahar', 'vakit',
          'büyük', 'balık', 'vefa', 'bulut', 'borç', 'varlık', 'bilgi', 'bayrak', 'barış', 'vurgu',
          'vicdan', 'bakış', 'vatan', 'bahar', 'vakit', 'büyük', 'balık', 'bulut', 'varlık', 'bilgi',
          'vefa', 'borç', 'bayrak', 'barış', 'vurgu', 'bavul', 'bana', 'var', 'bu', 've'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 2,
      },
      {
        id: 'u3-l3',
        unitId: 3,
        title: 'Sağ Alt Sıra: N ve M Tuşları',
        description: 'Sağ el işaret ve orta parmak aşağı inişleri: Türkçenin en çok kullanılan sessizleri.',
        icon: '🎯',
        targetChars: ['n', 'm'],
        words: [
          'ne', 'mu', 'man', 'nam', 'anlam', 'zaman', 'insan', 'orman', 'liman', 'mimar',
          'namus', 'mevsim', 'müzik', 'makine', 'nokta', 'nitelik', 'merak', 'mektup', 'nesil', 'millet',
          'insan', 'zaman', 'anlam', 'orman', 'liman', 'mimar', 'mevsim', 'müzik', 'makine', 'nokta',
          'nitelik', 'merak', 'mektup', 'nesil', 'millet', 'namus', 'nam', 'man', 'mu', 'ne'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 30,
        minAccuracy: 93,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u3-l4',
        unitId: 3,
        title: 'Türkçe Alt Sıra: Ö ve Ç Tuşları',
        description: 'Türkçe klavyenin sağ alt tarafında yer alan Ö ve Ç harfleriyle akıcı yazım.',
        icon: '🇹🇷',
        targetChars: ['ö', 'ç'],
        words: [
          'ön', 'çok', 'çöl', 'öbek', 'çiçek', 'çözüm', 'örnek', 'çıkış', 'özlem', 'çocuk',
          'öğrenim', 'çalışma', 'çare', 'özgür', 'çevre', 'önder', 'çizgi', 'özen', 'çelik', 'özet',
          'çiçek', 'çözüm', 'örnek', 'çıkış', 'özlem', 'çocuk', 'çalışma', 'özgür', 'çevre', 'önder',
          'öğrenim', 'çare', 'çizgi', 'özen', 'çelik', 'özet', 'öbek', 'çöl', 'çok', 'ön'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 30,
        minAccuracy: 93,
        xpReward: 40,
        gemReward: 3,
      },
      {
        id: 'u3-l5',
        unitId: 3,
        title: 'Üç Sıranın Entegrasyonu',
        description: 'Üst sıra, ev sırası ve alt sırayı harmanlayan zengin sözcük kombinasyonları.',
        icon: '💎',
        targetChars: ['all'],
        words: [
          'müzisyen', 'çözümlemek', 'özgürlük', 'vizyoner', 'başlangıç', 'zamanlama', 'kararlılık', 'bağımsızlık',
          'fedakarlık', 'yetenekli', 'gözlemci', 'büyüleyici', 'araştırma', 'uygarlık', 'cumhuriyet', 'aydınlanma',
          'müzisyen', 'çözümlemek', 'özgürlük', 'vizyoner', 'başlangıç', 'zamanlama', 'kararlılık', 'bağımsızlık',
          'fedakarlık', 'yetenekli', 'gözlemci', 'büyüleyici', 'araştırma', 'uygarlık', 'cumhuriyet', 'aydınlanma'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 34,
        minAccuracy: 94,
        xpReward: 45,
        gemReward: 3,
      },
      {
        id: 'u3-l6',
        unitId: 3,
        title: 'Tüm Klavye Entegrasyon Sınavı',
        description: 'Tüm harf sırasını kesintisiz ve hatasız ritimle birbirine bağlayan zorlu sınav.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'cumhuriyet', 'aydınlanma', 'özgürlük', 'bağımsızlık', 'kararlılık', 'başlangıç', 'zamanlama', 'vizyoner',
          'çözümlemek', 'müzisyen', 'araştırma', 'uygarlık', 'fedakarlık', 'yetenekli', 'gözlemci', 'büyüleyici',
          'insanlık', 'tarih boyunca', 'özgür düşünceyi', 'savunan', 'büyük fikirler', 'sayesinde', 'ilerlemiştir',
          'çalışkanlık', 've', 'azim', 'her türlü engeli', 'aşmanın', 'yegane', 'anahtarıdır'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 36,
        minAccuracy: 95,
        xpReward: 60,
        gemReward: 6,
      },
    ],
  },
  {
    id: 4,
    title: 'Ünite 4: Shift ve Büyük Harf Disiplini',
    description: 'Sol ve sağ Shift tuşu koordinasyonu: Özel isimler, başlıklar ve cümle başlangıçları.',
    themeColor: '#ec4899',
    lessons: [
      {
        id: 'u4-l1',
        unitId: 4,
        title: 'Sol Shift ile Sağ El Harfleri',
        description: 'Sol serçe parmakla Shift basarken sağ elinle büyük harf yazma tekniği.',
        icon: '⇧',
        targetChars: ['Shift', 'J', 'K', 'L', 'U', 'I', 'O', 'P'],
        words: [
          'Kemal', 'Lale', 'Orhan', 'Pelin', 'İlhan', 'Umut', 'Kadir', 'Oğuz', 'Leyla', 'Jale',
          'Karadeniz', 'Pamukkale', 'Kapadokya', 'Lübnan', 'Osmaniye', 'Polatlı', 'İzmir', 'Konya', 'Ordu', 'Kars',
          'Kemal', 'Lale', 'Orhan', 'Pelin', 'İlhan', 'Umut', 'Kadir', 'Oğuz', 'Leyla', 'Jale',
          'Karadeniz', 'Pamukkale', 'Kapadokya', 'Lübnan', 'Osmaniye', 'Polatlı', 'İzmir', 'Konya', 'Ordu', 'Kars'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 92,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u4-l2',
        unitId: 4,
        title: 'Sağ Shift ile Sol El Harfleri',
        description: 'Sağ serçe parmakla Shift basarken sol elinle büyük harf yazma tekniği.',
        icon: '⇧',
        targetChars: ['Shift', 'A', 'S', 'D', 'F', 'E', 'R', 'T'],
        words: [
          'Ahmet', 'Selim', 'Deniz', 'Fatih', 'Emre', 'Rıza', 'Tarık', 'Ali', 'Selin', 'Derya',
          'Ankara', 'Samsun', 'Diyarbakır', 'Erzurum', 'Trabzon', 'Antalya', 'Edirne', 'Tekirdağ', 'Sivas', 'Bursa',
          'Ahmet', 'Selim', 'Deniz', 'Fatih', 'Emre', 'Rıza', 'Tarık', 'Ali', 'Selin', 'Derya',
          'Ankara', 'Samsun', 'Diyarbakır', 'Erzurum', 'Trabzon', 'Antalya', 'Edirne', 'Tekirdağ', 'Sivas', 'Bursa'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 92,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u4-l3',
        unitId: 4,
        title: 'Özel İsimler ve Şehirler',
        description: 'Türkiye ve dünya coğrafyasından özel isimleri Shift disipliniyle akıcı yaz.',
        icon: '🗺️',
        targetChars: ['all'],
        words: [
          'İstanbul', 'Ankara', 'İzmir', 'Bursa', 'Antalya', 'Adana', 'Trabzon', 'Eskişehir', 'Gaziantep', 'Konya',
          'Türkiye', 'Almanya', 'Fransa', 'İtalya', 'İspanya', 'Japonya', 'Kanada', 'Brezilya', 'Avustralya', 'İsveç',
          'Mustafa', 'Kemal', 'Atatürk', 'Nazım', 'Hikmet', 'Sabahattin', 'Ali', 'Halide', 'Edip', 'Adıvar',
          'Yaşar', 'Kemal', 'Ahmet', 'Hamdi', 'Tanpınar', 'Oğuz', 'Atay', 'Cahit', 'Sıtkı', 'Tarancı'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 32,
        minAccuracy: 94,
        xpReward: 45,
        gemReward: 3,
      },
      {
        id: 'u4-l4',
        unitId: 4,
        title: 'Cümle Başı ve Kısaltmalar',
        description: 'Büyük harfle başlayan cümleler, resmi kısaltmalar (TBMM, TDK, ASELSAN, TÜBİTAK).',
        icon: '🏛️',
        targetChars: ['all'],
        words: [
          'Türkiye', 'Büyük', 'Millet', 'Meclisi', 'TBMM', 'tarafından', 'kabul', 'edilen', 'yeni', 'kanun',
          'Türk', 'Dil', 'Kurumu', 'TDK', 'sözlüğünde', 'yer', 'alan', 'kelimeler', 'büyük', 'önem',
          'TÜBİTAK', 've', 'ASELSAN', 'tarafından', 'geliştirilen', 'yerli', 'teknoloji', 'projeleri', 'hızla', 'büyüyor',
          'Geleceğin', 'dijital', 'dünyasında', 'bilim', 've', 'teknoloji', 'öncü', 'rol', 'oynamaktadır'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 34,
        minAccuracy: 94,
        xpReward: 50,
        gemReward: 3,
      },
      {
        id: 'u4-l5',
        unitId: 4,
        title: 'Shift Koordinasyon Sınavı',
        description: 'Büyük ve küçük harf dengesini ölçen yüksek odaklanma testi.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'Mustafa', 'Kemal', 'Atatürk', '19 Mayıs', '1919', 'yılında', 'Samsun', 'şehrine', 'çıkarak', 'Kurtuluş',
          'Savaşı', 'meşalesini', 'yaktı.', 'Türkiye', 'Cumhuriyeti', 'ilelebet', 'payidar', 'kalacaktır.',
          'Ankara', 'başkent', 'olarak', 'milli', 'mücadelenin', 'kalbi', 'olmuş,', 'milletin', 'azim', 've',
          'kararı', 'her', 'türlü', 'güçlüğün', 'üstesinden', 'gelmeyi', 'başarmıştır.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 36,
        minAccuracy: 95,
        xpReward: 60,
        gemReward: 6,
      },
    ],
  },
  {
    id: 5,
    title: 'Ünite 5: Noktalama İşaretleri ve Metin İçi Ritim',
    description: 'Nokta, virgül, noktalı virgül, iki nokta, tırnak, soru işareti ve parantezler.',
    themeColor: '#f59e0b',
    lessons: [
      {
        id: 'u5-l1',
        unitId: 5,
        title: 'Nokta ve Virgül Refleksleri',
        description: 'Cümle bitişleri ve nefes alma durakları: Noktadan ve virgülden sonra boşluk bırakma refleksi.',
        icon: '✍️',
        targetChars: ['.', ',', ' '],
        words: [
          'Zaman,', 'en', 'kıymetli', 'hazinedir.', 'Sabır,', 'başarının', 'anahtarıdır.', 'Çalışmak,', 'insanı', 'özgürleştirir.',
          'Kitaplar,', 'sessiz', 'öğretmenlerdir.', 'Bilgi,', 'paylaştıkça', 'çoğalır.', 'Sanat,', 'ruhun', 'aynasıdır.',
          'Doğruluk,', 'en', 'büyük', 'erdemdir.', 'Hayat,', 'öğrenmeye', 'değer', 'bir', 'yolculuktur.',
          'Azim,', 'kararlılık,', 'disiplin', 've', 'odaklanma,', 'her', 'hedefe', 'ulaştırır.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 32,
        minAccuracy: 94,
        xpReward: 45,
        gemReward: 2,
      },
      {
        id: 'u5-l2',
        unitId: 5,
        title: 'Noktalı Virgül ve İki Nokta: ; ve :',
        description: 'Bağlantılı cümleler ve açıklama blokları.',
        icon: '🪶',
        targetChars: [';', ':'],
        words: [
          'At', 'ölür,', 'meydan', 'kalır;', 'yiğit', 'ölür,', 'şan', 'kalır.', 'Hedefimiz', 'bellidir:', 'en', 'iyisi', 'olmak.',
          'Başarı', 'üç', 'şeye', 'bağlıdır:', 'çalışmak,', 'odaklanmak', 've', 'vazgeçmemek.', 'Hava', 'karardı;', 'yolcular', 'dağıldı.',
          'Öğretmen', 'şöyle', 'dedi:', 'bilgi', 'sahibi', 'olmadan', 'fikir', 'sahibi', 'olunamaz.',
          'Kelimeler', 'tükendi;', 'sessizlik', 'bütün', 'salonu', 'kapladı.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 34,
        minAccuracy: 94,
        xpReward: 45,
        gemReward: 2,
      },
      {
        id: 'u5-l3',
        unitId: 5,
        title: 'Tırnak, Kesme ve Soru İşaretleri: ", \', ?',
        description: 'Alıntılar, kesme işaretiyle ayrılan ekler ve soru cümleleri.',
        icon: '❓',
        targetChars: ['"', "'", '?'],
        words: [
          '"Gelecek,', 'hayallerine', 'inananlarındır"', 'sözü', 'ne', 'kadar', 'doğru?', 'Türkiye\'nin', 'başkenti', 'neresidir?',
          'Atatürk\'ün', '"Yurtta', 'sulh,', 'cihanda', 'sulh"', 'ilkesini', 'biliyor', 'musunuz?', 'İstanbul\'un', 'tarihi', 'dokusu', 'büyüleyici.',
          '"Neden', 'duruyoruz?', 'Hemen', 'başlamalıyız"', 'dedi.', 'Bugün', 'kaç', 'kelime', 'yazdın?',
          'Yarınki', 'toplantı', 'saat', 'kaçta', 'başlayacak?'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 35,
        minAccuracy: 95,
        xpReward: 50,
        gemReward: 3,
      },
      {
        id: 'u5-l4',
        unitId: 5,
        title: 'Ünlem, Tire ve Parantezler: !, -, ()',
        description: 'Duygu patlamaları, ara sözler ve parantez içi açıklamalar.',
        icon: '❗',
        targetChars: ['!', '-', '(', ')'],
        words: [
          'Dikkat!', 'Bu', 'bir', 'uyarıdır!', 'Daktilo', '(on', 'parmak)', 'yazımı', 'büyük', 'bir', 'ayrıcalıktır.',
          'Kurtuluş', 'Savaşı', '(1919-1923)', 'milletimizin', 'bağımsızlık', 'destanıdır!', 'Yaşasın', 'özgürlük!',
          'Hızlı', 'yazmak', '-eğer', 'doğruluk', 'yoksa-', 'hiçbir', 'anlam', 'ifade', 'etmez!',
          'Teknoloji', '(yapay', 'zeka', 've', 'otomasyon)', 'dünyayı', 'yeniden', 'şekillendiriyor.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 36,
        minAccuracy: 95,
        xpReward: 50,
        gemReward: 3,
      },
      {
        id: 'u5-l5',
        unitId: 5,
        title: 'Noktalama Ustası Sınavı',
        description: 'Tüm noktalama işaretlerini zengin diyaloglar ve karmaşık cümlelerle harmanlayan sınav.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'Sokrat', 'şöyle', 'demişti:', '"Bildiğim', 'tek', 'şey,', 'hiçbir', 'şey', 'bilmediğimdir."', 'Peki,', 'biz', 'öğrenmeye', 'hazır', 'mıyız?',
          'Elbette!', 'İnsan', '-eğer', 'isterse-', 'bütün', 'zorlukları', 'yenebilir.', 'Türkiye\'nin', 'çağdaşlaşma', 'yolculuğu', '(1923\'ten', 'bugüne)',
          'kesintisiz', 'sürmektedir;', 'çünkü', 'bilim,', 'akıl', 've', 'sanat', 'milletin', 'rehberidir!'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 38,
        minAccuracy: 96,
        xpReward: 65,
        gemReward: 6,
      },
    ],
  },
  {
    id: 6,
    title: 'Ünite 6: Rakamlar ve Nümerik Satır',
    description: 'Sayı satırı (1-0), tarihler, para birimleri, matematiksel ve istatistiksel veriler.',
    themeColor: '#0ea5e9',
    lessons: [
      {
        id: 'u6-l1',
        unitId: 6,
        title: 'Sol El Sayıları: 1, 2, 3, 4, 5',
        description: 'Sol el parmaklarının üst sayı satırına yukarı çapraz uzanımları.',
        icon: '🔢',
        targetChars: ['1', '2', '3', '4', '5'],
        words: [
          '12', '34', '51', '2026', '1453', '1024', '404', '500', '360', '1984',
          '123', '451', '234', '512', '314', '425', '135', '241', '532', '115',
          '1923', '1071', '1453', '2024', '2025', '2026', '100', '250', '350', '450',
          '551', '432', '321', '124', '235', '341', '412', '523', '134', '251'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 26,
        minAccuracy: 92,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u6-l2',
        unitId: 6,
        title: 'Sağ El Sayıları: 6, 7, 8, 9, 0',
        description: 'Sağ el parmaklarının üst sayı satırına yukarı çapraz uzanımları.',
        icon: '🔢',
        targetChars: ['6', '7', '8', '9', '0'],
        words: [
          '78', '90', '67', '2080', '1999', '8080', '999', '700', '888', '606',
          '789', '980', '678', '890', '769', '870', '968', '607', '809', '708',
          '1980', '1990', '2000', '2010', '2020', '2030', '660', '770', '880', '990',
          '67890', '98760', '70809', '80906', '90607', '80709', '60807', '70908', '80609', '90807'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 26,
        minAccuracy: 92,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u6-l3',
        unitId: 6,
        title: 'Tarihler, Saatler ve Formatlar',
        description: 'Takvim günleri, ISO formatları, saatler ve telefon blokları.',
        icon: '📅',
        targetChars: ['all'],
        words: [
          '2026-09-14', '1923-10-29', '1453-05-29', '1919-05-19', '1071-08-26', 'saat', '14:30:00', 'sabah', '09:15', 'gece', '23:45',
          'telefon:', '+90', '(555)', '123-4567', 'posta', 'kodu:', '34700', 'oda', 'no:', '402', 'kat:', '12',
          '2026-01-01', 'tarihli', 'rapora', 'göre', 'toplam', 'satış', 'adedi', '1.450', 'olarak', 'kaydedildi.',
          'Sistem', 'güncellemesi', 'saat', '03:00', 'ile', '05:00', 'arasında', 'yapılacaktır.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 32,
        minAccuracy: 94,
        xpReward: 50,
        gemReward: 3,
      },
      {
        id: 'u6-l4',
        unitId: 6,
        title: 'Finans, Para Birimleri ve Yüzdeler',
        description: '₺, $, €, %, +, -, = ve ondalık basamaklar.',
        icon: '💰',
        targetChars: ['all'],
        words: [
          '1.250,50₺', '$450.00', '€2.800', '%18.5', 'KDV', 'dahil', 'fiyat:', '15.750₺', 'iskonto:', '%12',
          'USD/TRY', 'paritesi', 'güncellendi.', 'Toplam', 'ciro:', '125.000€', 'net', 'kar:', '%24.8',
          'Hesap', 'özeti:', 'gelir', '=', '45.000₺', '-', 'gider', '=', '18.500₺', 'fark', '=', '26.500₺',
          'Yıllık', 'büyüme', 'oranı', '%8.4', 'olarak', 'beklenmektedir.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 34,
        minAccuracy: 94,
        xpReward: 55,
        gemReward: 3,
      },
      {
        id: 'u6-l5',
        unitId: 6,
        title: 'Sayı ve Finans Sınavı',
        description: 'Karmaşık finansal tablolar, tarihler ve sayısal verileri hatasız yazma sınavı.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'Şirketimizin', '2026', 'yılı', 'ilk', 'çeyrek', 'gelirleri', '1.450.000₺', 'seviyesine', 'ulaştı.',
          'Bu', 'rakam', 'geçen', 'yılın', 'aynı', 'dönemine', 'göre', '%18.6', 'artış', 'anlamına', 'gelmektedir.',
          'Toplam', 'ihracat', 'tutarı', '$320.000', 've', '€145.500', 'olarak', 'gerçekleşmiştir.',
          '2026-12-31', 'tarihine', 'kadar', 'hedefimiz', 'net', 'karı', '%25', 'seviyesinde', 'korumaktır.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 36,
        minAccuracy: 95,
        xpReward: 70,
        gemReward: 6,
      },
    ],
  },
  {
    id: 7,
    title: 'Ünite 7: Yüksek Hız ve Dayanıklılık Koridoru',
    description: 'En sık kullanılan 1000 Türkçe kelime ile 50+ WPM hız maratonu ve parmak dayanıklılığı.',
    themeColor: '#ef4444',
    lessons: [
      {
        id: 'u7-l1',
        unitId: 7,
        title: 'En Sık 500 Kelime Akışı',
        description: 'Kelimeleri harf harf değil, zihinde bir blok olarak algılayıp ışık hızında yaz.',
        icon: '⚡',
        targetChars: ['all'],
        words: [
          'bir', 've', 'bu', 'da', 'de', 'için', 'ile', 'ne', 'gibi', 'çok',
          'daha', 'kadar', 'sonra', 'kendi', 'en', 'her', 'olan', 'var', 'ben', 'o',
          'zaman', 'büyük', 'gün', 'yeni', 'ilk', 'iyi', 'yok', 'nasıl', 'diye', 'biz',
          'şimdi', 'böyle', 'bütün', 'ancak', 'son', 'bana', 'biri', 'bile', 'insan', 'önce'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 42,
        minAccuracy: 95,
        xpReward: 55,
        gemReward: 2,
      },
      {
        id: 'u7-l2',
        unitId: 7,
        title: 'Ritmik Hece ve Çift Harf Blokları',
        description: 'Çift sesli/sessiz harflerde (ll, mm, tt, ss, kk) parmak sekmelerini pürüzsüzleştir.',
        icon: '🥁',
        targetChars: ['all'],
        words: [
          'dikkat', 'millet', 'kuvvet', 'hürriyet', 'şiddet', 'cennet', 'minnet', 'lezzet', 'izzet', 'hiddet',
          'hassas', 'maddesi', 'külliyat', 'tahsis', 'tecessüs', 'müddet', 'mükemmel', 'tavassut', 'mürettebat', 'şeffaf',
          'milletin', 'hürriyet', 've', 'istiklal', 'aşkı', 'tarihin', 'her', 'döneminde', 'en', 'büyük',
          'kuvvet', 'kaynağı', 'olmuştur.', 'Dikkat', 've', 'hassasiyetle', 'çalışan', 'zihinler', 'başarıya', 'ulaşır.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 45,
        minAccuracy: 95,
        xpReward: 60,
        gemReward: 2,
      },
      {
        id: 'u7-l3',
        unitId: 7,
        title: '50+ WPM Hız Bariyeri',
        description: 'Yüksek tempo koridoruna giriş: Düşünce hızında klavye kullanımı.',
        icon: '🚀',
        targetChars: ['all'],
        words: [
          'Hızlı', 'yazmak', 'yalnızca', 'parmakların', 'değil,', 'aynı', 'zamanda', 'odaklanmış', 'bir', 'zihnin',
          'eseridir.', 'Her', 'tuş', 'vuruşunda', 'ritmi', 'koru,', 'asla', 'tereddüt', 'etme', 've',
          'kelimelerin', 'akışına', 'kendini', 'bırak.', 'Doğruluk', 've', 'süreklilik', 'sağlandığında', 'hız', 'kendiliğinden',
          'ortaya', 'çıkacaktır.', 'Klavye', 'artık', 'senin', 'doğal', 'bir', 'uzantın', 'haline', 'geldi.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 50,
        minAccuracy: 96,
        xpReward: 70,
        gemReward: 3,
      },
      {
        id: 'u7-l4',
        unitId: 7,
        title: '100 Kelimelik Dayanıklılık Testi',
        description: 'Parmak yorgunluğuna karşı kas hafızasını ve yüksek doğruluğu koruma antrenmanı.',
        icon: '🏃',
        targetChars: ['all'],
        words: [
          'İnsan', 'zihni', 'sürekli', 'gelişime', 've', 'öğrenmeye', 'açık', 'muazzam', 'bir', 'mekanizmadır.',
          'Daktilo', 'sanatı,', 'düşünceleri', 'anında', 'yazıya', 'dökebilme', 'özgürlüğü', 'kazandırır.',
          'Sabırla', 've', 'disiplinle', 'yapılan', 'her', 'pratik,', 'seni', 'bir', 'adım', 'daha',
          'ileri', 'taşır.', 'Hatasız', 've', 'akıcı', 'yazabilmek,', 'dijital', 'çağın', 'en', 'değerli',
          'yeteneklerinden', 'biridir.', 'Kendine', 'güven,', 'ellerini', 'rahat', 'bırak', 've', 'ritmi',
          'asla', 'kaybetme.', 'Her', 'gün', 'biraz', 'daha', 'hızlanacaksın.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 52,
        minAccuracy: 96,
        xpReward: 80,
        gemReward: 3,
      },
      {
        id: 'u7-l5',
        unitId: 7,
        title: 'Hız Fırtınası Final Sınavı',
        description: '60 WPM ve %96 doğruluk barajını devirerek hız madalyasını kazan.',
        icon: '👑',
        targetChars: ['all'],
        words: [
          'Saniyede', 'onlarca', 'harf', 'üreten', 'parmaklar,', 'düşüncenin', 'ışık', 'hızına', 'eriştiğini', 'müjdeler.',
          'Odaklanma', 'zirvededir;', 'dikkat', 'dağıtıcı', 'hiçbir', 'unsur', 'bu', 'kusursuz', 'akışı', 'bozamaz.',
          'Klavye', 'üzerinde', 'uçuşan', 'parmaklar,', 'zamanın', 've', 'mekanın', 'ötesinde', 'bir', 'uyumla',
          'çalışmaktadır.', 'Sen', 'artık', 'sıradan', 'bir', 'kullanıcı', 'değil,', 'gerçek', 'bir', 'hız', 'efsanesisin!'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 58,
        minAccuracy: 96,
        xpReward: 100,
        gemReward: 7,
      },
    ],
  },
  {
    id: 8,
    title: 'Ünite 8: Türk Edebiyatı ve Usta Yazarlar',
    description: 'Sabahattin Ali, Nazım Hikmet, Sait Faik, Oğuz Atay ve Atatürk\'ün ölümsüz eserleriyle edebi derinlik.',
    themeColor: '#d97706',
    lessons: [
      {
        id: 'u8-l1',
        unitId: 8,
        title: 'Sabahattin Ali — Kürk Mantolu Madonna',
        description: 'Duygusal derinlik, içsel monolog ve zengin tasvir dili.',
        icon: '📖',
        targetChars: ['all'],
        words: [
          'İçimde', 'hiçbir', 'şeye', 'karşı', 'bir', 'istek,', 'bir', 'heves', 'kalmamıştı.',
          'Yalnızdım.', 'Dünyada', 'bana', 'bunu', 'unutturacak', 'hiçbir', 'şey', 'yoktu.',
          'Fakat', 'onunla', 'karşılaştığım', 'o', 'ilk', 'an,', 'bütün', 'hayatımın', 'en',
          'aydınlık,', 'en', 'unutulmaz', 'dönüm', 'noktası', 'oldu.', 'İnsanları', 'sevmeyi',
          'yeniden', 'öğrendim.', 'Kelimelerin', 'yetmediği', 'yerde', 'bakışlar', 'konuşurdu.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 40,
        minAccuracy: 95,
        xpReward: 65,
        gemReward: 3,
      },
      {
        id: 'u8-l2',
        unitId: 8,
        title: 'Nazım Hikmet — Davet ve Umut Şiiri',
        description: 'Ritmik, coşkulu ve akıcı şiirsel mısraların daktilo harmonisi.',
        icon: '🕊️',
        targetChars: ['all'],
        words: [
          'Dörtnala', 'gelip', 'Uzak', 'Asya\'dan', 'Akdeniz\'e', 'bir', 'kısrak', 'başı', 'gibi', 'uzanan',
          'bu', 'memleket,', 'bizim.', 'Bilekler', 'kan', 'içinde,', 'dişler', 'kenetli,', 'ayaklar', 'çıplak',
          've', 'ipek', 'bir', 'halıya', 'benzeyen', 'toprak,', 'bu', 'cehennem,', 'bu', 'cennet', 'bizim.',
          'Yaşamak', 'bir', 'ağaç', 'gibi', 'tek', 've', 'hür', 've', 'bir', 'orman', 'gibi', 'kardeşçesine,',
          'bu', 'hasret', 'bizim.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 42,
        minAccuracy: 95,
        xpReward: 70,
        gemReward: 3,
      },
      {
        id: 'u8-l3',
        unitId: 8,
        title: 'Sait Faik Abasıyanık — Haritada Bir Nokta',
        description: 'İstanbul öykücülüğünün sıcak, samimi ve duru anlatımı.',
        icon: '🌊',
        targetChars: ['all'],
        words: [
          'Yazmasam', 'deli', 'olacaktım.', 'Söz', 'vermiştim', 'kendi', 'kendime:', 'yazmayacaktım.',
          'Ama', 'dayanamadım.', 'Kalemi,', 'kağıdı', 'aldım.', 'Balıkçıların', 'sesleri,', 'denizin',
          'tuzlu', 'kokusu,', 'martıların', 'çığlıkları', 'içime', 'doldu.', 'İnsanları', 'seviyordum;',
          'onların', 'derdini,', 'neşesini,', 'alın', 'terini', 'kelimelerle', 'yaşatmak', 'zorundaydım.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 44,
        minAccuracy: 96,
        xpReward: 75,
        gemReward: 3,
      },
      {
        id: 'u8-l4',
        unitId: 8,
        title: 'Oğuz Atay — Tutunamayanlar',
        description: 'Zihinsel monolog, ironi ve derin edebi cümle dizilimi.',
        icon: '🎭',
        targetChars: ['all'],
        words: [
          'Kelimeler,', 'albayım,', 'bazı', 'anlamlara', 'gelmiyor.', 'İnsan', 'bazen', 'susmalı,',
          'bazen', 'de', 'bütün', 'dünyaya', 'haykırmalı.', 'Biz', 'hayatı', 'kitaplardan', 'öğrenmeye',
          'çalışan', 'insanlardık;', 'oysa', 'hayat', 'sokaklarda,', 'yağmurun', 'altında,', 'bekleyişlerdeydi.',
          'Beni', 'anlamak', 'için', 'biraz', 'yorulmanız', 'gerekecek,', 'albayım.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 46,
        minAccuracy: 96,
        xpReward: 80,
        gemReward: 3,
      },
      {
        id: 'u8-l5',
        unitId: 8,
        title: 'Mustafa Kemal Atatürk — Gençliğe Hitabe',
        description: 'Tarihi hitabet gücü, yüksek odaklanma ve milli bilinç metni.',
        icon: '🇹🇷',
        targetChars: ['all'],
        words: [
          'Ey', 'Türk', 'gençliği!', 'Birinci', 'vazifen,', 'Türk', 'istiklâlini,', 'Türk', 'Cumhuriyetini,',
          'ilelebet', 'muhafaza', 've', 'müdafaa', 'etmektir.', 'Mevcudiyetinin', 've', 'istikbalinin',
          'yegâne', 'temeli', 'budur.', 'Bu', 'temel,', 'senin', 'en', 'kıymetli', 'hazinendir.',
          'Muhtaç', 'olduğun', 'kudret,', 'damarlarındaki', 'asil', 'kanda', 'mevcuttur!'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 50,
        minAccuracy: 97,
        xpReward: 90,
        gemReward: 4,
      },
      {
        id: 'u8-l6',
        unitId: 8,
        title: 'Edebiyat Ustalık Belgesi Sınavı',
        description: 'Büyük Türk edebiyatı klasiklerinden derlenen kapsamlı edebi hız testi.',
        icon: '📜',
        targetChars: ['all'],
        words: [
          'Sanatsız', 'kalan', 'bir', 'milletin', 'hayat', 'damarlarından', 'biri', 'kopmuş', 'demektir.',
          'Edebiyat,', 'bir', 'toplumun', 'vicdanı,', 'hafızası', 've', 'geleceğe', 'bıraktığı', 'en', 'büyük',
          'mirasıdır.', 'Kelimelerin', 'gücüyle', 'inşa', 'edilen', 'dünyalar,', 'zamanın', 've', 'mekanın',
          'yıkıcı', 'etkisine', 'karşı', 'ebediyen', 'dimdik', 'ayakta', 'kalacaktır.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 52,
        minAccuracy: 97,
        xpReward: 110,
        gemReward: 7,
      },
    ],
  },
  {
    id: 9,
    title: 'Ünite 9: Geliştirici, Terminal ve Kod Sözdizimi',
    description: 'Bash, PowerShell, Git, TypeScript, SQL, Docker ve Python gerçek kod komutları.',
    themeColor: '#06b6d4',
    lessons: [
      {
        id: 'u9-l1',
        unitId: 9,
        title: 'Git ve Terminal Temelleri',
        description: 'Her yazılımcının parmak refleksi olması gereken terminal ve sürüm kontrol komutları.',
        icon: '💻',
        targetChars: ['all'],
        words: [
          'git', 'status', 'git', 'add', '.', 'git', 'commit', '-m', '"feat: implement typeflow engine"',
          'git', 'push', 'origin', 'main', 'git', 'checkout', '-b', 'feature/auth', 'npm', 'install',
          'npm', 'run', 'build', 'npm', 'run', 'dev', 'npx', 'next', 'telemetry', 'disable',
          'git', 'rebase', 'main', 'git', 'pull', '--rebase', 'origin', 'main'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 38,
        minAccuracy: 95,
        xpReward: 65,
        gemReward: 3,
      },
      {
        id: 'u9-l2',
        unitId: 9,
        title: 'PowerShell ve Sistem Betikleri',
        description: 'Windows terminali, pipe operatörleri ve sistem yönetimi komutları.',
        icon: '⚙️',
        targetChars: ['all'],
        words: [
          'Get-Process', '|', 'Where-Object', 'CPU', '-gt', '10', '|', 'Select-Object', 'Name,', 'Id',
          'Stop-Service', '-Name', '"wuauserv"', '-Force', 'Set-ExecutionPolicy', 'RemoteSigned', '-Scope', 'CurrentUser',
          'Test-NetConnection', '-ComputerName', '"tiyatrotist.com.tr"', '-Port', '443', 'Get-ChildItem', '-Recurse',
          'New-Item', '-Path', '"./config"', '-ItemType', 'Directory', '-Force'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 40,
        minAccuracy: 95,
        xpReward: 70,
        gemReward: 3,
      },
      {
        id: 'u9-l3',
        unitId: 9,
        title: 'Modern TypeScript ve React Sentaksı',
        description: 'Generics, arrow functions, async/await ve React 19 Hooks.',
        icon: '💠',
        targetChars: ['all'],
        words: [
          'export', 'interface', 'User<T>', '{', 'id:', 'string;', 'data:', 'T;', '}',
          'const', 'fetchData', '=', 'async', '():', 'Promise<Response>', '=>', '{', 'return', 'await', 'api.get();', '}',
          'const', '[count,', 'setCount]', '=', 'useState<number>(0);', 'useEffect(()', '=>', '{', 'console.log(count);', '},', '[count]);',
          'export', 'default', 'function', 'Component({', 'children', '}:', 'Props)', '{', 'return', '<div>{children}</div>;', '}'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 44,
        minAccuracy: 96,
        xpReward: 80,
        gemReward: 3,
      },
      {
        id: 'u9-l4',
        unitId: 9,
        title: 'SQL ve İlişkisel Veritabanı Sorguları',
        description: 'SELECT, JOIN, WHERE, GROUP BY ve karmaşık indeksleme komutları.',
        icon: '🗄️',
        targetChars: ['all'],
        words: [
          'SELECT', 'u.id,', 'u.username,', 'COUNT(t.id)', 'AS', 'test_count', 'FROM', 'users', 'u',
          'LEFT', 'JOIN', 'tests', 't', 'ON', 'u.id', '=', 't.user_id', 'WHERE', 't.wpm', '>=', '60',
          'GROUP', 'BY', 'u.id,', 'u.username', 'HAVING', 'COUNT(t.id)', '>', '10', 'ORDER', 'BY', 'test_count', 'DESC;'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 45,
        minAccuracy: 96,
        xpReward: 85,
        gemReward: 4,
      },
      {
        id: 'u9-l5',
        unitId: 9,
        title: 'Docker, Python ve YAML Yapılandırması',
        description: 'Kapsayıcı yönetimi, Python veri analiz blokları ve Kubernetes manifestleri.',
        icon: '🐳',
        targetChars: ['all'],
        words: [
          'docker', 'compose', 'up', '-d', '--build', 'docker', 'ps', '-a', 'docker', 'logs', '-f', 'backend',
          'import', 'numpy', 'as', 'np;', 'data', '=', '[x**2', 'for', 'x', 'in', 'range(100)]',
          'version:', '"3.8"', 'services:', 'web:', 'image:', 'node:20-alpine', 'ports:', '["3000:3000"]',
          'def', 'calculate_metrics(wpm:', 'float,', 'acc:', 'float)', '->', 'dict:', 'return', '{"score":', 'wpm', '*', 'acc}'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 46,
        minAccuracy: 96,
        xpReward: 90,
        gemReward: 4,
      },
      {
        id: 'u9-l6',
        unitId: 9,
        title: 'Full-Stack Hackathon Bitirme Sınavı',
        description: 'Gerçek geliştirici dünyasından harmanlanmış zorlu kod ve CLI maratonu.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'export', 'default', 'async', 'function', 'handler(req:', 'NextApiRequest,', 'res:', 'NextApiResponse)', '{',
          'if', '(req.method', '!==', '"POST")', 'return', 'res.status(405).json({', 'error:', '"Method', 'Not', 'Allowed"', '});',
          'const', '{', 'token,', 'score', '}', '=', 'req.body;', 'const', 'verified', '=', 'await', 'verifySession(token);',
          'if', '(!verified)', 'throw', 'new', 'Error("Unauthorized");', 'return', 'res.status(200).json({', 'success:', 'true', '});', '}'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 50,
        minAccuracy: 97,
        xpReward: 120,
        gemReward: 7,
      },
    ],
  },
  {
    id: 10,
    title: 'Ünite 10: Daktilo Grand Master & Hız Koridoru',
    description: 'Daktilo Akademisinin nihai zirvesi: 65+ WPM, edebi felsefe, kod blokları ve büyük mezuniyet maratonu.',
    themeColor: '#8b5cf6',
    lessons: [
      {
        id: 'u10-l1',
        unitId: 10,
        title: 'Karmaşık Metin ve Rakam Maratonu',
        description: 'Harf, büyük harf, noktalama ve rakamların kesintisiz ritmik entegrasyonu.',
        icon: '⚡',
        targetChars: ['all'],
        words: [
          'Dijital', 'çağda', 'her', 'saniye', 'milyonlarca', 'veri', 'akışı', 'gerçekleşiyor.', '2026', 'yılında',
          'yapay', 'zeka', '(AI)', 'teknolojileri', '%45.8', 'oranında', 'büyüme', 'kaydetti.', 'Yazılımcılar', 've',
          'düşünürler,', 'bu', 'hızlı', 'dönüşüme', 'ayak', 'uydurmak', 'için', 'öğrenme', 'kapasitelerini', 'en',
          'üst', 'düzeye', 'çıkarmalıdır.', 'Başarı,', 'odaklanmış', 'zihinlerin', 'doğal', 'bir', 'sonucudur.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 55,
        minAccuracy: 96,
        xpReward: 90,
        gemReward: 4,
      },
      {
        id: 'u10-l2',
        unitId: 10,
        title: 'Maksimum Doğruluk Sınavı (%98 Barajı)',
        description: 'Tek bir hata yapmadan tam doğrulukla ve yüksek hızla yazma disiplini.',
        icon: '🎯',
        targetChars: ['all'],
        words: [
          'Kusursuzluk', 'bir', 'eylem', 'değil,', 'bir', 'alışkanlıktır.', 'Parmakların', 'her', 'hareketi,', 'yılların',
          'birikimi', 've', 'disiplinli', 'çalışmanın', 'bir', 'yansımasıdır.', 'Hata', 'yapmaktan', 'korkma;',
          'ancak', 'her', 'hatadan', 'ders', 'çıkararak', 'kendini', 'sürekli', 'geliştir.', 'Zihnini', 'boşalt,',
          'yalnızca', 'karşındaki', 'metne', 've', 'tuşların', 'ritmine', 'odaklan.', 'Kusursuz', 'doğruluk', 'senin', 'elindedir.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 56,
        minAccuracy: 98,
        xpReward: 100,
        gemReward: 5,
      },
      {
        id: 'u10-l3',
        unitId: 10,
        title: '65+ WPM Zirve Sprinti',
        description: 'Daktilo dünyasının en yüksek hız katmanına adım at.',
        icon: '🏎️',
        targetChars: ['all'],
        words: [
          'Rüzgar', 'gibi', 'esen', 'parmaklar,', 'klavyenin', 'üzerinde', 'adeta', 'dans', 'ediyor.', 'Saniyeler',
          'içinde', 'onlarca', 'kelime', 'ekranda', 'beliriyor.', 'Düşünce', 've', 'eylem', 'arasındaki', 'bütün',
          'engeller', 'ortadan', 'kalktı.', 'Sen', 'artık', 'kelimelerle', 'ışık', 'hızında', 'iletişim', 'kuruyorsun.',
          'Bu', 'tempo,', 'dijital', 'dünyanın', 'efsanelerine', 'özgü', 'bir', 'ustalık', 'düzeyidir!'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 65,
        minAccuracy: 96,
        xpReward: 120,
        gemReward: 5,
      },
      {
        id: 'u10-l4',
        unitId: 10,
        title: 'Dijital Çağın Daktilosu: Felsefe ve Teknoloji',
        description: 'Teknolojinin insani değerlerle ve felsefeyle buluştuğu manifesto metni.',
        icon: '🌌',
        targetChars: ['all'],
        words: [
          'Makineler', 'hızlanır,', 'algoritmalar', 'gelişir;', 'fakat', 'anlam', 'yaratan', 'daima', 'insan', 'zihnidir.',
          'Yazdığımız', 'her', 'cümle,', 'geleceğin', 'kültürel', 'mirasına', 'eklenen', 'bir', 'tuğladır.',
          'Teknolojiyi', 'yalnızca', 'tüketen', 'değil,', 'onu', 'bilinçle,', 'sanatla', 've', 'felsefeyle', 'şekillendiren',
          'bireyler', 'olmalıyız.', 'Daktilo', 'bu', 'yolda', 'bizim', 'en', 'güçlü', 've', 'en', 'sadık', 'aracımızdır.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 58,
        minAccuracy: 97,
        xpReward: 110,
        gemReward: 5,
      },
      {
        id: 'u10-l5',
        unitId: 10,
        title: 'Daktilo Grand Master: Nihai Mezuniyet Projesi',
        description: 'Daktilo Akademisi\'nin en prestijli bitirme unvanı: Grand Master.',
        icon: '👑',
        targetChars: ['all'],
        words: [
          'Tebrikler!', 'Ev', 'sırasının', 'ilk', 'tuşları', 'olan', 'F', 've', 'J', 'harfleriyle', 'başlayan', 'bu',
          'uzun', 'yolculuk,', 'seni', 'gerçek', 'bir', 'Daktilo', 'Grand', 'Master', 'seviyesine', 'ulaştırdı.',
          'Artık', 'klavye', 'senin', 'parmaklarının', 'doğal', 'bir', 'uzantısı;', 'düşüncelerin', 'hiçbir', 'kesintiye',
          'uğramadan', 'dijital', 'evrene', 'akıyor.', 'Bu', 'disiplin,', 'sana', 'hayatın', 'her', 'alanında',
          'büyük', 'bir', 'odaklanma', 've', 'özgüven', 'kazandıracaktır.', 'Başarıların', 'daim', 'olsun!'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 65,
        minAccuracy: 98,
        xpReward: 200,
        gemReward: 10,
      },
    ],
  },
];

// ─── 1. B. DAKTİLO AKADEMİSİ: 10 KAPSAMLI ÜNİTE VE 50+ DERS (ENGLISH) ─────────
export const ACADEMY_UNITS_EN: Unit[] = [
  {
    id: 1,
    title: 'Unit 1: Home Row Fundamentals',
    description: 'Anchor keys: A, S, D, F and J, K, L, ; keys. Guide bumps and finger discipline.',
    themeColor: '#3b82f6',
    lessons: [
      {
        id: 'u1-l1',
        unitId: 1,
        title: 'Anchor Keys: F and J',
        description: 'Locate tactile bumps and practice smooth index finger cadence.',
        icon: '☝️',
        targetChars: ['f', 'j', ' '],
        words: [
          'f', 'j', 'ff', 'jj', 'fj', 'jf', 'fjf', 'jfj', 'fjjf', 'jffj',
          'fff', 'jjj', 'fjfj', 'jfjf', 'fjj', 'jff', 'jfjfj', 'fjfjf', 'ffjj', 'jjff',
          'f', 'j', 'ff', 'jj', 'jf', 'fj', 'fjf', 'jfj', 'ffj', 'jjf',
          'fjfj', 'jfjf', 'fjjf', 'jffj', 'fff', 'jjj', 'fj', 'jf', 'f', 'j'
        ],
        stars: 0,
        status: 'active',
        minWpm: 18,
        minAccuracy: 92,
        xpReward: 25,
        gemReward: 2,
      },
      {
        id: 'u1-l2',
        unitId: 1,
        title: 'Left Hand Home Row: A, S, D, F',
        description: 'Position left fingers on home keys and build core words.',
        icon: '👈',
        targetChars: ['a', 's', 'd', 'f'],
        words: [
          'as', 'sad', 'fad', 'dad', 'falls', 'salsa', 'flask', 'salad', 'daffy', 'fads',
          'adds', 'sads', 'flak', 'alas', 'façade', 'dadas', 'salas', 'flask', 'falls', 'salad',
          'dad', 'sad', 'fad', 'as', 'salsa', 'flak', 'alas', 'falls', 'salad', 'flask',
          'daffy', 'fads', 'adds', 'dadas', 'salas', 'sad', 'fad', 'dad', 'as', 'falls'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 20,
        minAccuracy: 92,
        xpReward: 30,
        gemReward: 2,
      },
      {
        id: 'u1-l3',
        unitId: 1,
        title: 'Right Hand Home Row: J, K, L, ;',
        description: 'Right hand home row coordination and semicolon reach.',
        icon: '👉',
        targetChars: ['j', 'k', 'l', ';'],
        words: [
          'ask', 'all', 'fall', 'lad', 'glad', 'flask', 'alas', 'kala', 'shall', 'skill',
          'kall', 'alls', 'lads', 'flaks', 'asks', 'falls', 'glads', 'shall', 'skill', 'flask',
          'ask', 'all', 'fall', 'lad', 'glad', 'flask', 'alas', 'kala', 'shall', 'skill',
          'kall', 'alls', 'lads', 'flaks', 'asks', 'falls', 'glads', 'shall', 'skill', 'flask'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 22,
        minAccuracy: 92,
        xpReward: 30,
        gemReward: 2,
      },
      {
        id: 'u1-l4',
        unitId: 1,
        title: 'Two-Hand Home Row Cadence',
        description: 'Alternate left and right fingers smoothly across the entire home row.',
        icon: '⚖️',
        targetChars: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        words: [
          'flash', 'salad', 'flask', 'falls', 'glass', 'alfalfa', 'dallas', 'slash', 'skiff', 'shall',
          'flask', 'glass', 'salad', 'flash', 'dallas', 'alfalfa', 'slash', 'falls', 'shall', 'skiff',
          'flash', 'salad', 'flask', 'falls', 'glass', 'alfalfa', 'dallas', 'slash', 'skiff', 'shall',
          'flask', 'glass', 'salad', 'flash', 'dallas', 'alfalfa', 'slash', 'falls', 'shall', 'skiff'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 25,
        minAccuracy: 93,
        xpReward: 35,
        gemReward: 3,
      },
      {
        id: 'u1-l5',
        unitId: 1,
        title: 'Home Row Sentence Flow',
        description: 'Type natural rhythmic phrases using strictly home row characters.',
        icon: '📜',
        targetChars: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        words: [
          'all', 'lads', 'ask', 'a', 'glad', 'dad', 'a', 'sad', 'lad', 'falls',
          'a', 'flask', 'falls', 'all', 'lads', 'shall', 'ask', 'a', 'glad', 'dad',
          'all', 'lads', 'ask', 'a', 'glad', 'dad', 'a', 'sad', 'lad', 'falls',
          'a', 'flask', 'falls', 'all', 'lads', 'shall', 'ask', 'a', 'glad', 'dad'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 26,
        minAccuracy: 94,
        xpReward: 40,
        gemReward: 3,
      },
      {
        id: 'u1-l6',
        unitId: 1,
        title: 'Home Row Checkpoint & Exam',
        description: 'Complete the home row exam with zero visual keyboard inspection.',
        icon: '🏆',
        targetChars: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
        words: [
          'all', 'glad', 'lads', 'shall', 'ask', 'a', 'sad', 'dad', 'a', 'flask',
          'falls', 'all', 'flash', 'glass', 'salad', 'dallas', 'alfalfa', 'skiff', 'slash', 'shall',
          'all', 'glad', 'lads', 'shall', 'ask', 'a', 'sad', 'dad', 'a', 'flask',
          'falls', 'all', 'flash', 'glass', 'salad', 'dallas', 'alfalfa', 'skiff', 'slash', 'shall'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 95,
        xpReward: 50,
        gemReward: 5,
      },
    ],
  },
  {
    id: 2,
    title: 'Unit 2: Top Row Extensions',
    description: 'Upward finger reaches: Q, W, E, R, T, Y, U, I, O, P keys.',
    themeColor: '#10b981',
    lessons: [
      {
        id: 'u2-l1',
        unitId: 2,
        title: 'Core Top Row: E and R',
        description: 'Master the most frequent vowels and consonants in English.',
        icon: '⚡',
        targetChars: ['e', 'r'],
        words: [
          'are', 'red', 'era', 'rare', 'dear', 'fear', 'free', 'reef', 'tree', 'feed',
          'seer', 'dare', 'fare', 'fade', 'read', 'reef', 'flee', 'deer', 'peer', 'beer',
          'are', 'red', 'era', 'rare', 'dear', 'fear', 'free', 'reef', 'tree', 'feed',
          'seer', 'dare', 'fare', 'fade', 'read', 'reef', 'flee', 'deer', 'peer', 'beer'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 24,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 2,
      },
      {
        id: 'u2-l2',
        unitId: 2,
        title: 'Center Reaches: T and Y',
        description: 'Index finger stretches to the center upper deck.',
        icon: '🎯',
        targetChars: ['t', 'y'],
        words: [
          'try', 'yet', 'they', 'year', 'stay', 'tray', 'fate', 'rate', 'gate', 'hate',
          'city', 'duty', 'easy', 'play', 'gray', 'pray', 'stay', 'tray', 'they', 'year',
          'try', 'yet', 'they', 'year', 'stay', 'tray', 'fate', 'rate', 'gate', 'hate',
          'city', 'duty', 'easy', 'play', 'gray', 'pray', 'stay', 'tray', 'they', 'year'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 25,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 2,
      },
      {
        id: 'u2-l3',
        unitId: 2,
        title: 'Right Top Row: U, I, O, P',
        description: 'Right hand upper row flexibility and vowel integration.',
        icon: '🖐️',
        targetChars: ['u', 'ı', 'o', 'p'],
        words: [
          'you', 'out', 'our', 'put', 'pour', 'poor', 'pure', 'pipe', 'plot', 'port',
          'part', 'post', 'spot', 'stop', 'trip', 'drop', 'open', 'poet', 'hope', 'rope',
          'you', 'out', 'our', 'put', 'pour', 'poor', 'pure', 'pipe', 'plot', 'port',
          'part', 'post', 'spot', 'stop', 'trip', 'drop', 'open', 'poet', 'hope', 'rope'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 27,
        minAccuracy: 93,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u2-l4',
        unitId: 2,
        title: 'Left Top Row: Q and W',
        description: 'Left pinky and ring finger reaches for rapid developer typing.',
        icon: '🌐',
        targetChars: ['q', 'w'],
        words: [
          'web', 'war', 'was', 'way', 'word', 'work', 'wire', 'quit', 'quick', 'quiet',
          'queen', 'quote', 'query', 'power', 'tower', 'water', 'write', 'wrong', 'sweet', 'sweep',
          'web', 'war', 'was', 'way', 'word', 'work', 'wire', 'quit', 'quick', 'quiet',
          'queen', 'quote', 'query', 'power', 'tower', 'water', 'write', 'wrong', 'sweet', 'sweep'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 93,
        xpReward: 40,
        gemReward: 3,
      },
      {
        id: 'u2-l5',
        unitId: 2,
        title: 'Top Row Mastery Exam',
        description: 'Full integration of home and top rows in challenging multi-syllable prose.',
        icon: '🌟',
        targetChars: ['all'],
        words: [
          'proper', 'report', 'writer', 'poetry', 'pretty', 'yellow', 'quarter', 'require', 'quality', 'request',
          'power', 'tower', 'water', 'write', 'wrong', 'sweet', 'sweep', 'queen', 'quote', 'query',
          'proper', 'report', 'writer', 'poetry', 'pretty', 'yellow', 'quarter', 'require', 'quality', 'request',
          'power', 'tower', 'water', 'write', 'wrong', 'sweet', 'sweep', 'queen', 'quote', 'query'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 32,
        minAccuracy: 95,
        xpReward: 55,
        gemReward: 5,
      },
    ],
  },
  {
    id: 3,
    title: 'Unit 3: Bottom Row Foundations',
    description: 'Down reaches: Z, X, C, V, B, N, M keys.',
    themeColor: '#8b5cf6',
    lessons: [
      {
        id: 'u3-l1',
        unitId: 3,
        title: 'Left Bottom Row: Z, X, C',
        description: 'Left pinky, ring, and middle downward reaches.',
        icon: '⚓',
        targetChars: ['z', 'x', 'c'],
        words: [
          'can', 'cat', 'car', 'case', 'city', 'zero', 'zone', 'zinc', 'zeal', 'next',
          'taxi', 'exam', 'axis', 'core', 'code', 'calm', 'cozy', 'maze', 'size', 'lazy',
          'can', 'cat', 'car', 'case', 'city', 'zero', 'zone', 'zinc', 'zeal', 'next',
          'taxi', 'exam', 'axis', 'core', 'code', 'calm', 'cozy', 'maze', 'size', 'lazy'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 27,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 2,
      },
      {
        id: 'u3-l2',
        unitId: 3,
        title: 'Center Bottom Row: V and B',
        description: 'Index finger stretches to lower center keys.',
        icon: '🌊',
        targetChars: ['v', 'b'],
        words: [
          'van', 'vat', 'vet', 'vote', 'view', 'very', 'vast', 'vivid', 'valve', 'vocal',
          'ban', 'bat', 'bet', 'boat', 'blue', 'bear', 'bold', 'brave', 'brain', 'build',
          'van', 'vat', 'vet', 'vote', 'view', 'very', 'vast', 'vivid', 'valve', 'vocal',
          'ban', 'bat', 'bet', 'boat', 'blue', 'bear', 'bold', 'brave', 'brain', 'build'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 2,
      },
      {
        id: 'u3-l3',
        unitId: 3,
        title: 'Right Bottom Row: N and M',
        description: 'Right index and middle fingers dropping into the bottom row.',
        icon: '🎯',
        targetChars: ['n', 'm'],
        words: [
          'man', 'men', 'mine', 'moon', 'mind', 'name', 'near', 'nest', 'noon', 'nine',
          'main', 'mean', 'more', 'most', 'make', 'next', 'need', 'note', 'news', 'nice',
          'man', 'men', 'mine', 'moon', 'mind', 'name', 'near', 'nest', 'noon', 'nine',
          'main', 'mean', 'more', 'most', 'make', 'next', 'need', 'note', 'news', 'nice'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 30,
        minAccuracy: 93,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u3-l4',
        unitId: 3,
        title: 'Full Three-Tier Keyboard Integration',
        description: 'Fluid movement uniting all three alphabetical rows.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'machine', 'movement', 'civilization', 'revolution', 'victory', 'bravery', 'balance', 'zenith',
          'horizon', 'dynamic', 'vibrant', 'freedom', 'explore', 'journey', 'network', 'system',
          'machine', 'movement', 'civilization', 'revolution', 'victory', 'bravery', 'balance', 'zenith',
          'horizon', 'dynamic', 'vibrant', 'freedom', 'explore', 'journey', 'network', 'system'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 34,
        minAccuracy: 95,
        xpReward: 55,
        gemReward: 5,
      },
    ],
  },
  {
    id: 4,
    title: 'Unit 4: Capitalization & Shift Mastery',
    description: 'Left and right Shift discipline, proper nouns, and capitalized sentence structures.',
    themeColor: '#ec4899',
    lessons: [
      {
        id: 'u4-l1',
        unitId: 4,
        title: 'Opposite Shift Discipline',
        description: 'Using opposite pinky for Shift to maintain balanced posture.',
        icon: '⇧',
        targetChars: ['Shift'],
        words: [
          'London', 'Paris', 'Tokyo', 'Berlin', 'Madrid', 'Rome', 'Austin', 'Boston', 'Denver', 'Miami',
          'Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack',
          'London', 'Paris', 'Tokyo', 'Berlin', 'Madrid', 'Rome', 'Austin', 'Boston', 'Denver', 'Miami',
          'Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 30,
        minAccuracy: 93,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u4-l2',
        unitId: 4,
        title: 'Acronyms and Formal Titles',
        description: 'NASA, MIT, IBM, UNESCO, and multi-capital abbreviations.',
        icon: '🏛️',
        targetChars: ['all'],
        words: [
          'NASA', 'launched', 'a', 'new', 'satellite.', 'MIT', 'researchers', 'published', 'breakthrough', 'AI',
          'models.', 'IBM', 'and', 'Cisco', 'partnered', 'for', 'global', 'cloud', 'security.', 'The',
          'United', 'Nations', 'announced', 'new', 'environmental', 'goals', 'for', '2030.', 'Keep',
          'striving', 'for', 'excellence', 'in', 'every', 'endeavor.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 34,
        minAccuracy: 94,
        xpReward: 50,
        gemReward: 3,
      },
      {
        id: 'u4-l3',
        unitId: 4,
        title: 'Capitalization Exam',
        description: 'Test high-speed Shift coordination under demanding paragraph flows.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'The', 'Declaration', 'of', 'Independence', 'was', 'signed', 'in', 'Philadelphia.', 'George', 'Washington',
          'led', 'the', 'Continental', 'Army', 'to', 'victory.', 'Today,', 'the', 'United', 'States',
          'stands', 'as', 'a', 'beacon', 'of', 'liberty', 'and', 'democratic', 'ideals', 'across', 'the', 'globe.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 36,
        minAccuracy: 95,
        xpReward: 60,
        gemReward: 5,
      },
    ],
  },
  {
    id: 5,
    title: 'Unit 5: Punctuation & Complex Cadence',
    description: 'Commas, periods, semicolons, quotes, exclamation, and parentheses.',
    themeColor: '#f59e0b',
    lessons: [
      {
        id: 'u5-l1',
        unitId: 5,
        title: 'Commas and Periods',
        description: 'Natural pauses and stops: comma and period spacing discipline.',
        icon: '✍️',
        targetChars: ['.', ',', ' '],
        words: [
          'Time,', 'like', 'a', 'river,', 'flows', 'forward.', 'Patience,', 'persistence,', 'and', 'dedication',
          'lead', 'to', 'mastery.', 'Books,', 'silent', 'mentors,', 'open', 'doors', 'to', 'unknown',
          'worlds.', 'Knowledge,', 'when', 'shared,', 'multiplies.', 'Never', 'give', 'up', 'on', 'your', 'dreams.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 34,
        minAccuracy: 94,
        xpReward: 45,
        gemReward: 2,
      },
      {
        id: 'u5-l2',
        unitId: 5,
        title: 'Quotes, Questions, and Semicolons',
        description: 'Dialogue, philosophical questions, and connected clauses.',
        icon: '❓',
        targetChars: ['"', '?', ';', ':'],
        words: [
          'He', 'asked:', '"What', 'is', 'the', 'meaning', 'of', 'courage?"', 'She', 'replied;', '"Courage', 'is',
          'not', 'the', 'absence', 'of', 'fear,', 'but', 'the', 'triumph', 'over', 'it."', 'Why', 'hesitate?',
          'The', 'future', 'belongs', 'to', 'those', 'who', 'dare', 'to', 'build', 'it.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 36,
        minAccuracy: 95,
        xpReward: 50,
        gemReward: 3,
      },
      {
        id: 'u5-l3',
        unitId: 5,
        title: 'Punctuation Mastery Exam',
        description: 'Complex literary prose saturated with punctuation.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          '"To', 'be,', 'or', 'not', 'to', 'be:', 'that', 'is', 'the', 'question;"', 'wrote', 'Shakespeare',
          'in', 'Hamlet.', 'Whether', '\'tis', 'nobler', 'in', 'the', 'mind', 'to', 'suffer', 'the', 'slings',
          'and', 'arrows', 'of', 'outrageous', 'fortune,', 'or', 'to', 'take', 'arms', 'against', 'a', 'sea',
          'of', 'troubles,', 'and', 'by', 'opposing', 'end', 'them?'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 38,
        minAccuracy: 96,
        xpReward: 65,
        gemReward: 5,
      },
    ],
  },
  {
    id: 6,
    title: 'Unit 6: Number Row & Financial Data',
    description: 'Numbers 1-0, dates, currencies ($, €, £), percentages, and mathematical stats.',
    themeColor: '#0ea5e9',
    lessons: [
      {
        id: 'u6-l1',
        unitId: 6,
        title: 'Numbers: 1 to 0',
        description: 'Upper numerical deck reaches.',
        icon: '🔢',
        targetChars: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
        words: [
          '10', '25', '50', '100', '1984', '2026', '404', '8080', '1453', '1024',
          '360', '720', '1080', '1440', '2160', '3840', '500', '750', '999', '1000',
          '10', '25', '50', '100', '1984', '2026', '404', '8080', '1453', '1024',
          '360', '720', '1080', '1440', '2160', '3840', '500', '750', '999', '1000'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 92,
        xpReward: 40,
        gemReward: 2,
      },
      {
        id: 'u6-l2',
        unitId: 6,
        title: 'Currencies, Dates, and Financial Metrics',
        description: 'Balance sheets, ISO timestamps, and financial figures.',
        icon: '💰',
        targetChars: ['all'],
        words: [
          'On', '2026-09-14,', 'revenue', 'exceeded', '$1,450,000,', 'representing', 'a', '+18.5%', 'increase.',
          'Operating', 'costs', 'dropped', 'to', '€320,000', 'with', 'net', 'margins', 'at', '24.2%.',
          'Stock', 'ticker', 'NASDAQ:TECH', 'rose', 'by', '5.4%', 'during', 'trading', 'hours.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 34,
        minAccuracy: 94,
        xpReward: 55,
        gemReward: 3,
      },
      {
        id: 'u6-l3',
        unitId: 6,
        title: 'Number Row Exam',
        description: 'Rigorous financial and numerical transcript.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'In', 'Q1', '2026,', 'global', 'cloud', 'expenditure', 'hit', '$620.5', 'billion.', 'Approximately',
          '45.8%', 'of', 'enterprises', 'migrated', 'workloads', 'to', 'serverless', 'architectures.',
          'Latency', 'decreased', 'from', '120ms', 'to', '18ms,', 'generating', 'an', 'estimated', '$3.2B', 'in', 'productivity', 'gains.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 36,
        minAccuracy: 95,
        xpReward: 70,
        gemReward: 5,
      },
    ],
  },
  {
    id: 7,
    title: 'Unit 7: High-Velocity Speed Corridor',
    description: 'High frequency words, smooth digraphs, and breaking through 50+ WPM.',
    themeColor: '#ef4444',
    lessons: [
      {
        id: 'u7-l1',
        unitId: 7,
        title: 'Top 300 English Core Vocabulary',
        description: 'Eliminate hesitation by recognizing full word shapes instantly.',
        icon: '⚡',
        targetChars: ['all'],
        words: [
          'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'I',
          'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at',
          'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she',
          'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 45,
        minAccuracy: 95,
        xpReward: 55,
        gemReward: 2,
      },
      {
        id: 'u7-l2',
        unitId: 7,
        title: 'Sprint Corridor: 60+ WPM',
        description: 'High-octane cadence pushing reflexes to the absolute boundary.',
        icon: '🚀',
        targetChars: ['all'],
        words: [
          'Speed', 'is', 'a', 'byproduct', 'of', 'accuracy', 'and', 'calm', 'focus.', 'When', 'fingers',
          'glide', 'effortlessly', 'across', 'switches,', 'typing', 'transforms', 'into', 'an', 'art',
          'form.', 'Maintain', 'even', 'breathing,', 'trust', 'your', 'muscle', 'memory,', 'and', 'accelerate.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 60,
        minAccuracy: 96,
        xpReward: 75,
        gemReward: 3,
      },
      {
        id: 'u7-l3',
        unitId: 7,
        title: 'Velocity Sprint Checkpoint',
        description: 'Prove sustained endurance at breakneck typing speeds.',
        icon: '👑',
        targetChars: ['all'],
        words: [
          'The', 'true', 'master', 'does', 'not', 'think', 'about', 'letters', 'or', 'words.', 'Thoughts',
          'stream', 'directly', 'from', 'consciousness', 'into', 'digital', 'expression.', 'You', 'have',
          'shattered', 'the', 'sound', 'barrier', 'of', 'the', 'keyboard.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 65,
        minAccuracy: 96,
        xpReward: 100,
        gemReward: 6,
      },
    ],
  },
  {
    id: 8,
    title: 'Unit 8: World Literature Classics',
    description: 'Shakespeare, George Orwell, Ernest Hemingway, and Virginia Woolf.',
    themeColor: '#d97706',
    lessons: [
      {
        id: 'u8-l1',
        unitId: 8,
        title: 'George Orwell — 1984',
        description: 'Dystopian clarity and stark narrative prose.',
        icon: '📖',
        targetChars: ['all'],
        words: [
          'It', 'was', 'a', 'bright', 'cold', 'day', 'in', 'April,', 'and', 'the', 'clocks', 'were',
          'striking', 'thirteen.', 'Winston', 'Smith,', 'his', 'chin', 'nuzzled', 'into', 'his', 'breast',
          'in', 'an', 'effort', 'to', 'escape', 'the', 'vile', 'wind,', 'slipped', 'quickly', 'through',
          'the', 'glass', 'doors', 'of', 'Victory', 'Mansions.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 44,
        minAccuracy: 95,
        xpReward: 65,
        gemReward: 3,
      },
      {
        id: 'u8-l2',
        unitId: 8,
        title: 'Ernest Hemingway — The Old Man and the Sea',
        description: 'Crisp, legendary minimalist sentence architecture.',
        icon: '🌊',
        targetChars: ['all'],
        words: [
          'He', 'was', 'an', 'old', 'man', 'who', 'fished', 'alone', 'in', 'a', 'skiff', 'in',
          'the', 'Gulf', 'Stream', 'and', 'he', 'had', 'gone', 'eighty-four', 'days', 'now', 'without',
          'taking', 'a', 'fish.', 'In', 'the', 'first', 'forty', 'days', 'a', 'boy', 'had', 'been',
          'with', 'him.', 'Man', 'is', 'not', 'made', 'for', 'defeat.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 46,
        minAccuracy: 96,
        xpReward: 75,
        gemReward: 3,
      },
      {
        id: 'u8-l3',
        unitId: 8,
        title: 'World Literature Exam',
        description: 'Classic literary excerpts demanding high focus and stamina.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'It', 'is', 'a', 'truth', 'universally', 'acknowledged,', 'that', 'a', 'single', 'man', 'in',
          'possession', 'of', 'a', 'good', 'fortune,', 'must', 'be', 'in', 'want', 'of', 'a',
          'wife.', 'However', 'little', 'known', 'the', 'feelings', 'or', 'views', 'of', 'such',
          'a', 'man', 'may', 'be', 'on', 'his', 'first', 'entering', 'a', 'neighbourhood.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 50,
        minAccuracy: 97,
        xpReward: 100,
        gemReward: 6,
      },
    ],
  },
  {
    id: 9,
    title: 'Unit 9: Developer & CLI Syntax',
    description: 'Git, Bash, TypeScript, SQL, and Docker real-world coding commands.',
    themeColor: '#06b6d4',
    lessons: [
      {
        id: 'u9-l1',
        unitId: 9,
        title: 'Git & Command Line Workflow',
        description: 'Essential shell commands every software engineer must internalize.',
        icon: '💻',
        targetChars: ['all'],
        words: [
          'git', 'checkout', '-b', 'feature/auth', 'git', 'add', '.', 'git', 'commit', '-m',
          '"feat(auth):', 'integrate', 'supabase', 'session"', 'git', 'push', 'origin', 'feature/auth',
          'pnpm', 'install', 'pnpm', 'build', 'pnpm', 'dev', 'docker', 'compose', 'up', '-d'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 42,
        minAccuracy: 95,
        xpReward: 70,
        gemReward: 3,
      },
      {
        id: 'u9-l2',
        unitId: 9,
        title: 'TypeScript & Modern React Hooks',
        description: 'Generics, functional components, and async API handlers.',
        icon: '💠',
        targetChars: ['all'],
        words: [
          'export', 'const', 'useAuth', '=', '<T,>():', 'AuthContext<T>', '=>', '{', 'const', 'context',
          '=', 'useContext(AuthContext);', 'if', '(!context)', 'throw', 'new', 'Error("Provider', 'missing");',
          'return', 'context;', '};', 'const', 'data', '=', 'await', 'res.json();'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 45,
        minAccuracy: 96,
        xpReward: 80,
        gemReward: 3,
      },
      {
        id: 'u9-l3',
        unitId: 9,
        title: 'Full-Stack Developer Hackathon',
        description: 'Advanced programming syntax across multiple languages.',
        icon: '🏆',
        targetChars: ['all'],
        words: [
          'SELECT', 'u.id,', 'u.email,', 'COUNT(t.id)', 'FROM', 'users', 'u', 'JOIN', 'tests', 't',
          'ON', 'u.id', '=', 't.user_id', 'WHERE', 't.wpm', '>=', '75', 'GROUP', 'BY', 'u.id',
          'HAVING', 'COUNT(t.id)', '>=', '50', 'ORDER', 'BY', 'COUNT(t.id)', 'DESC;'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 50,
        minAccuracy: 97,
        xpReward: 110,
        gemReward: 6,
      },
    ],
  },
  {
    id: 10,
    title: 'Unit 10: Grand Master Apex Marathon',
    description: 'The crowning achievement of TypeFlow: 65+ WPM, 98% accuracy, and Grand Master certification.',
    themeColor: '#8b5cf6',
    lessons: [
      {
        id: 'u10-l1',
        unitId: 10,
        title: 'Code & Narrative Convergence',
        description: 'Seamlessly shift between prose, numbers, and technical operators.',
        icon: '⚡',
        targetChars: ['all'],
        words: [
          'In', 'software', 'design,', 'clean', 'abstractions', 'determine', 'systemic', 'longevity.', 'Version',
          '2.4.0', 'introduced', 'low-latency', 'event', 'streaming,', 'reducing', 'P99', 'latencies', 'by', '64.2%.',
          'Developers', 'must', 'write', 'code', 'that', 'humans', 'can', 'comprehend', 'and', 'machines', 'can', 'execute', 'flawlessly.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 58,
        minAccuracy: 97,
        xpReward: 100,
        gemReward: 4,
      },
      {
        id: 'u10-l2',
        unitId: 10,
        title: 'Precision Gauntlet (98% Required)',
        description: 'Unforgiving accuracy requirement under sustained typing velocity.',
        icon: '🎯',
        targetChars: ['all'],
        words: [
          'Flawless', 'precision', 'is', 'not', 'an', 'accident;', 'it', 'is', 'the', 'culmination',
          'of', 'mindful', 'deliberate', 'practice.', 'Every', 'key', 'strike', 'must', 'be', 'intentional,',
          'measured,', 'and', 'steady.', 'Discard', 'haste;', 'embrace', 'true', 'clarity.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 60,
        minAccuracy: 98,
        xpReward: 120,
        gemReward: 5,
      },
      {
        id: 'u10-l3',
        unitId: 10,
        title: 'Grand Master Apex Final Exam',
        description: 'Complete the definitive TypeFlow graduation trial to earn the Grand Master title.',
        icon: '👑',
        targetChars: ['all'],
        words: [
          'Congratulations!', 'You', 'have', 'conquered', 'all', '10', 'units', 'of', 'TypeFlow', 'Academy.',
          'The', 'keyboard', 'is', 'no', 'longer', 'a', 'physical', 'tool', 'between', 'you', 'and', 'the', 'machine;',
          'it', 'is', 'an', 'effortless', 'conduit', 'of', 'your', 'creative', 'intelligence.', 'Welcome', 'to', 'the',
          'rank', 'of', 'Typing', 'Grand', 'Master.'
        ],
        stars: 0,
        status: 'locked',
        minWpm: 65,
        minAccuracy: 98,
        xpReward: 200,
        gemReward: 10,
      },
    ],
  },
];

// ─── STAGE GENERATOR: 3-STAGE DEEP PROGRESSION ────────────────────────────────
export function ensureLessonStages(lesson: Lesson, lang: Locale = 'tr'): LessonStage[] {
  if (lesson.stages && lesson.stages.length >= 3) {
    return lesson.stages;
  }
  const isTr = lang === 'tr';
  const chars = lesson.targetChars.filter(c => c !== 'all' && c !== ' ' && c !== 'Shift');

  // Stage 1: Kas Hafızası & Parmak Yerleşimi (25-35 words of focused drills)
  let drillWords: string[] = [];
  if (chars.length >= 2) {
    const a = chars[0];
    const b = chars[1];
    drillWords = [
      a, b, `${a}${b}`, `${b}${a}`, `${a}${a}`, `${b}${b}`, `${a}${b}${a}`, `${b}${a}${b}`,
      `${a}${a}${b}`, `${b}${b}${a}`, `${a}${b}${a}${b}`, `${b}${a}${b}${a}`, `${a}${b}${b}${a}`,
      `${b}${a}${a}${b}`, a, b, `${a}${b}`, `${b}${a}`, `${a}${a}${b}${b}`, `${b}${b}${a}${a}`,
      `${a}${b}${a}`, `${b}${a}${b}`, `${a}${b}${a}${b}`, `${b}${a}${b}${a}`, a, b, `${a}${b}`, `${b}${a}`
    ];
  } else if (chars.length === 1) {
    const a = chars[0];
    drillWords = [
      a, `${a}${a}`, `${a}${a}${a}`, a, `${a}${a}`, a, `${a}${a}${a}`, `${a}${a}`,
      a, a, `${a}${a}`, `${a}${a}${a}`, a, `${a}${a}`, a, `${a}${a}${a}`
    ];
  } else {
    drillWords = lesson.words.slice(0, 25);
  }

  // Stage 2: Kelime İnşası & Hız (35-50 words of rich vocabulary)
  const vocabWords = lesson.words.length >= 30
    ? lesson.words
    : [...lesson.words, ...lesson.words];

  // Stage 3: Akıcı Cümleler & Ustalık Sınavı (50-80 words of natural sentences)
  const sentenceFlow = isTr
    ? [
        lesson.title, 'kapsamında', 'öğrenilen', 'bütün', 'tuşları', 'kesintisiz', 've', 'akıcı', 'bir', 'ritimle',
        'yazmaya', 'odaklan.', 'Parmaklarını', 'ev', 'sırasından', 'ayırmadan,', 'klavyeye', 'hiç', 'bakmadan',
        'düşünce', 'hızında', 'yazma', 'disiplinini', 'koru.', 'Hatasız', 'vuruş', 'serileri', 've', 'yüksek',
        'konsantrasyon,', 'başarının', 'en', 'güvenilir', 'anahtarıdır.', 'Bu', 'aşama,', 'üniteyi', 'yıldızlarla',
        'tamamlaman', 'için', 'nihai', 'dayanıklılık', 've', 'akıcılık', 'sınavındır.', 'Kendine', 'güven', 've', 'başla!'
      ]
    : [
        'Focus', 'on', 'maintaining', 'a', 'fluid', 'and', 'unbroken', 'rhythm', 'for', lesson.title,
        'across', 'all', 'target', 'characters.', 'Keep', 'your', 'fingers', 'anchored', 'to', 'the', 'home',
        'row', 'and', 'trust', 'your', 'muscle', 'memory', 'completely.', 'Zero', 'visual', 'inspection',
        'and', 'continuous', 'focus', 'form', 'the', 'bedrock', 'of', 'elite', 'typing', 'cadence.',
        'Sustain', 'your', 'tempo,', 'breathe', 'naturally,', 'and', 'demonstrate', 'true', 'three-star',
        'mastery', 'in', 'this', 'final', 'endurance', 'trial.'
      ];

  return [
    {
      stageIndex: 1,
      title: isTr ? 'Aşama 1: Kas Hafızası & Parmak Yerleşimi' : 'Stage 1: Muscle Memory Drills',
      description: isTr ? 'Parmak konumlandırma ve ritmik tuş vuruş tekrarları.' : 'Key finger positioning and rhythmic repetition.',
      type: 'drill',
      targetChars: lesson.targetChars,
      words: drillWords,
      minWpm: Math.max(14, Math.round(lesson.minWpm * 0.75)),
      minAccuracy: Math.max(90, lesson.minAccuracy - 2),
    },
    {
      stageIndex: 2,
      title: isTr ? 'Aşama 2: Kelime İnşası & Hız' : 'Stage 2: Core Vocabulary & Speed',
      description: isTr ? 'Öğrenilen harflerle hedef kelime dağarcığını pekiştir.' : 'Reinforce vocabulary with target key combinations.',
      type: 'words',
      targetChars: lesson.targetChars,
      words: vocabWords,
      minWpm: lesson.minWpm,
      minAccuracy: lesson.minAccuracy,
    },
    {
      stageIndex: 3,
      title: isTr ? 'Aşama 3: Akıcı Cümleler & Ustalık Sınavı' : 'Stage 3: Flow Sentences & Star Mastery',
      description: isTr ? 'Noktalama, akışkanlık ve yıldız kazanma sınavı.' : 'Punctuation, natural cadence, and star mastery test.',
      type: 'sentences',
      targetChars: lesson.targetChars,
      words: sentenceFlow,
      minWpm: Math.round(lesson.minWpm * 1.1),
      minAccuracy: Math.min(98, lesson.minAccuracy + 2),
    },
  ];
}

export function getUnitsForLang(lang: Locale): Unit[] {
  const baseUnits = lang === 'tr' ? ACADEMY_UNITS_TR : ACADEMY_UNITS_EN;
  return baseUnits.map(unit => ({
    ...unit,
    lessons: unit.lessons.map(lesson => ({
      ...lesson,
      stages: ensureLessonStages(lesson, lang),
    })),
  }));
}

// ─── 2. DUOLINGO LİGLERİ (LEAGUES) ───────────────────────────────────────────
export const LEAGUE_TIERS: { id: LeagueTier; nameTr: string; nameEn: string; icon: string; minXp: number }[] = [
  { id: 'bronze', nameTr: 'Membran Çırakları', nameEn: 'Membrane Apprentices', icon: '🥉', minXp: 0 },
  { id: 'silver', nameTr: 'Mekanik Tuş Birliği', nameEn: 'Mechanical Switch Guild', icon: '🥈', minXp: 250 },
  { id: 'gold', nameTr: 'Kızıl Switch Locası', nameEn: 'Red Linear Swarm', icon: '🥇', minXp: 600 },
  { id: 'sapphire', nameTr: 'Kapasitif Usta Topluluğu', nameEn: 'Topre Capacitive Order', icon: '💎', minXp: 1200 },
  { id: 'diamond', nameTr: 'Daktilo Kozmosu // Optik Zirve', nameEn: 'Quantum Optical Overlord', icon: '👑', minXp: 2000 },
];

export const MOCK_LEAGUE_MEMBERS: Record<LeagueTier, LeagueMember[]> = {
  bronze: [
    { id: 'b1', username: 'cyber_phoenix', avatar: '🔥', weeklyXp: 280, rank: 1 },
    { id: 'b2', username: 'neo_coder', avatar: '⚡', weeklyXp: 245, rank: 2 },
    { id: 'b3', username: 'ghost_typist', avatar: '👻', weeklyXp: 210, rank: 3 },
    { id: 'b4', username: 'terminal_root', avatar: '🤖', weeklyXp: 160, rank: 4 },
    { id: 'b5', username: 'speedy_fox', avatar: '🦊', weeklyXp: 130, rank: 5 },
    { id: 'b6', username: 'retro_coder', avatar: '👾', weeklyXp: 95, rank: 6 },
    { id: 'b7', username: 'quantum_leap', avatar: '🌐', weeklyXp: 60, rank: 7 },
  ],
  silver: [
    { id: 's1', username: 'vortex_pulse', avatar: '🌀', weeklyXp: 490, rank: 1 },
    { id: 's2', username: 'neon_rider', avatar: '🏍️', weeklyXp: 430, rank: 2 },
    { id: 's3', username: 'matrix_hacker', avatar: '🕶️', weeklyXp: 380, rank: 3 },
    { id: 's4', username: 'syntax_witch', avatar: '🔮', weeklyXp: 310, rank: 4 },
    { id: 's5', username: 'pixel_monk', avatar: '🧘', weeklyXp: 260, rank: 5 },
  ],
  gold: [
    { id: 'g1', username: 'hyper_velocity', avatar: '🚀', weeklyXp: 820, rank: 1 },
    { id: 'g2', username: 'chronos_time', avatar: '⏳', weeklyXp: 750, rank: 2 },
    { id: 'g3', username: 'solaris_prime', avatar: '☀️', weeklyXp: 690, rank: 3 },
    { id: 'g4', username: 'apex_predator', avatar: '🦅', weeklyXp: 610, rank: 4 },
  ],
  sapphire: [
    { id: 'sp1', username: 'celestial_zen', avatar: '✨', weeklyXp: 1440, rank: 1 },
    { id: 'sp2', username: 'frost_byte', avatar: '❄️', weeklyXp: 1380, rank: 2 },
    { id: 'sp3', username: 'deep_ocean', avatar: '🌊', weeklyXp: 1290, rank: 3 },
  ],
  diamond: [
    { id: 'd1', username: 'omnipresent_god', avatar: '👑', weeklyXp: 2450, rank: 1 },
    { id: 'd2', username: 'speed_of_light', avatar: '⚡', weeklyXp: 2120, rank: 2 },
    { id: 'd3', username: 'singularity_ai', avatar: '🌌', weeklyXp: 1910, rank: 3 },
  ],
};

// ─── 3. ZORLAŞTIRILMIŞ GÜNLÜK GÖREVLER (DAILY QUESTS) ─────────────────────────
export function getDailyQuests(
  lang: Locale,
  userXpToday: number,
  testsToday: number,
  lessonsToday: number
): DailyQuest[] {
  const isTr = lang === 'tr';
  return [
    {
      id: 'quest-xp',
      title: isTr ? 'Günlük XP Barajı' : 'Daily XP Barrier',
      description: isTr ? 'Bugün en az 250 XP kazan' : 'Earn at least 250 XP today',
      icon: '⚡',
      current: Math.min(userXpToday, 250),
      target: 250,
      xpReward: 40,
      gemReward: 4,
      isCompleted: userXpToday >= 250,
      isClaimed: false,
    },
    {
      id: 'quest-tests',
      title: isTr ? 'Demir Parmaklar' : 'Iron Fingers',
      description: isTr ? 'Bugün 5 tam test veya pratik oturumu bitir' : 'Complete 5 full tests or practice drills today',
      icon: '⌨️',
      current: Math.min(testsToday, 5),
      target: 5,
      xpReward: 35,
      gemReward: 3,
      isCompleted: testsToday >= 5,
      isClaimed: false,
    },
    {
      id: 'quest-lesson',
      title: isTr ? 'Akademi Disiplini' : 'Academy Discipline',
      description: isTr ? 'Daktilo Akademisinde 3 ders aşamasını başarıyla geç' : 'Pass 3 academy lesson stages successfully',
      icon: '🗺️',
      current: Math.min(lessonsToday, 3),
      target: 3,
      xpReward: 50,
      gemReward: 4,
      isCompleted: lessonsToday >= 3,
      isClaimed: false,
    },
    {
      id: 'quest-accuracy',
      title: isTr ? 'Kusursuz Odaklanma' : 'Laser Focus',
      description: isTr ? 'En az %96 doğrulukla 3 oturum tamamla' : 'Finish 3 sessions with 96%+ accuracy',
      icon: '🎯',
      current: Math.min(testsToday >= 3 ? 3 : testsToday, 3),
      target: 3,
      xpReward: 45,
      gemReward: 5,
      isCompleted: testsToday >= 3,
      isClaimed: false,
    },
  ];
}

// ─── 4. ZORLAŞTIRILMIŞ BAŞARIMLAR (ACHIEVEMENTS) ─────────────────────────────
export function getAchievementsList(lang: Locale): Achievement[] {
  const isTr = lang === 'tr';
  return [
    {
      id: 'first-step',
      title: isTr ? 'İlk Adım' : 'First Step',
      description: isTr ? 'İlk yazım testini veya dersini başarıyla tamamla.' : 'Complete your very first test or lesson.',
      icon: '🌱',
      current: 0,
      target: 1,
      isUnlocked: false,
      rewardGems: 5,
    },
    {
      id: 'sniper-acc',
      title: isTr ? 'Keskin Nişancı (%98+ Doğruluk)' : 'Sniper Accuracy (98%+ Acc)',
      description: isTr ? '%98 veya üzeri doğrulukla en az 5 test bitir.' : 'Finish at least 5 tests with 98%+ accuracy.',
      icon: '🎯',
      current: 0,
      target: 5,
      isUnlocked: false,
      rewardGems: 10,
    },
    {
      id: 'speed-demon',
      title: isTr ? 'Hız Canavarı (60 WPM)' : 'Speed Demon (60 WPM)',
      description: isTr ? '60 WPM hız barajını aş.' : 'Break the 60 WPM speed barrier.',
      icon: '🏎️',
      current: 0,
      target: 60,
      isUnlocked: false,
      rewardGems: 10,
    },
    {
      id: 'speed-master',
      title: isTr ? 'Hız Ustası (80 WPM)' : 'Speed Master (80 WPM)',
      description: isTr ? '80 WPM hız barajını aş.' : 'Break the 80 WPM speed barrier.',
      icon: '🚀',
      current: 0,
      target: 80,
      isUnlocked: false,
      rewardGems: 15,
    },
    {
      id: 'light-speed',
      title: isTr ? 'Işık Hızı (100 WPM)' : 'Speed of Light (100 WPM)',
      description: isTr ? '100 WPM efsanevi hız bariyerini devir.' : 'Achieve 100+ WPM in any mode.',
      icon: '⚡',
      current: 0,
      target: 100,
      isUnlocked: false,
      rewardGems: 25,
    },
    {
      id: 'hypersonic',
      title: isTr ? 'Hipersonik Zirve (120 WPM)' : 'Hypersonic Apex (120 WPM)',
      description: isTr ? '120 WPM ile daktilo tanrıları katına yüksel.' : 'Achieve 120+ WPM in any typing mode.',
      icon: '👑',
      current: 0,
      target: 120,
      isUnlocked: false,
      rewardGems: 35,
    },
    {
      id: 'fire-keeper',
      title: isTr ? 'Ateş Muhafızı (7 Gün Seri)' : 'Fire Keeper (7-Day Streak)',
      description: isTr ? '7 günlük aralıksız pratik serisi yakala.' : 'Maintain a 7-day typing streak.',
      icon: '🔥',
      current: 0,
      target: 7,
      isUnlocked: false,
      rewardGems: 15,
    },
    {
      id: 'unbreakable-streak',
      title: isTr ? 'Bozulmaz İrade (30 Gün Seri)' : 'Unbreakable Will (30-Day Streak)',
      description: isTr ? 'Tam 30 gün boyunca her gün pratik yap.' : 'Maintain a 30-day streak unbroken.',
      icon: '🛡️',
      current: 0,
      target: 30,
      isUnlocked: false,
      rewardGems: 30,
    },
    {
      id: 'century-club',
      title: isTr ? 'Yüzler Kulübü (50 Test)' : 'Century Club (50 Tests)',
      description: isTr ? 'Toplam 50 test veya akademi dersi bitir.' : 'Complete 50 tests or academy lessons.',
      icon: '💯',
      current: 0,
      target: 50,
      isUnlocked: false,
      rewardGems: 15,
    },
    {
      id: 'typing-titan',
      title: isTr ? 'Daktilo Titanı (200 Test)' : 'Typing Titan (200 Tests)',
      description: isTr ? 'Toplam 200 test veya akademi dersi bitir.' : 'Complete 200 total tests or lessons.',
      icon: '🗿',
      current: 0,
      target: 200,
      isUnlocked: false,
      rewardGems: 30,
    },
    {
      id: 'code-ninja',
      title: isTr ? 'Kod & Terminal Cambazı' : 'Terminal Ninja',
      description: isTr ? 'Kod & CLI modunda 15 oturum tamamla.' : 'Complete 15 tests in Code & CLI mode.',
      icon: '🥷',
      current: 0,
      target: 15,
      isUnlocked: false,
      rewardGems: 15,
    },
    {
      id: 'gem-hoarder',
      title: isTr ? 'Elmas Hazinesi (100 Elmas)' : 'Gem Vault (100 Gems)',
      description: isTr ? 'Zorlu görevler ve derslerle 100 Elmas biriktir.' : 'Accumulate 100 scarce gems.',
      icon: '💎',
      current: 0,
      target: 100,
      isUnlocked: false,
      rewardGems: 20,
    },
  ];
}

// ─── 5. DENGELENMİŞ DUOLINGO MAĞAZASI (REBALANCED SHOP CATALOG) ───────────────
export function getShopCatalog(lang: Locale): ShopItem[] {
  const isTr = lang === 'tr';
  return [
    {
      id: 'super-typeflow',
      name: isTr ? '👑 Super TypeFlow (Pro SaaS Planı)' : '👑 Super TypeFlow (Pro Plan)',
      description: isTr
        ? 'Sınırsız Odak Enerjisi (♾️), Sıfır Reklam (🚫), Tüm Temalar & Mekanik Sesler Açık, 2X Hızlı XP ve Altın Profil Rozeti!'
        : 'Unlimited Focus Energy (♾️), Zero Ads (🚫), All Themes & Sounds Unlocked, 2X XP Boost and Golden Profile Glow!',
      icon: '👑',
      cost: 150,
      category: 'utility',
      owned: false,
    },
    {
      id: 'refill-energy',
      name: isTr ? '🔋 Odak Bataryasını Şarj Et (5/5)' : '🔋 Recharge Focus Battery (5/5)',
      description: isTr ? 'Akademi dersleri ve pratikler için bataryanı maksimum kapasiteye doldurur.' : 'Instantly restores full 5/5 focus battery for academy lessons.',
      icon: '🔋',
      cost: 20,
      category: 'utility',
      owned: false,
    },
    {
      id: 'streak-freeze',
      name: isTr ? 'Seri Dondurucu (Streak Freeze)' : 'Streak Freeze',
      description: isTr ? 'Bir gün yazmayı kaçırsan bile günlük serin korunur.' : 'Preserves your streak if you miss a day of practice.',
      icon: '🧊',
      cost: 40,
      category: 'utility',
      owned: false,
    },
    {
      id: 'theme-violet',
      name: isTr ? 'Tokyo Neon Mor Tema' : 'Tokyo Neon Violet Theme',
      description: isTr ? 'Siberpunk Tokyo gecelerinden ilham alan mor neon tema.' : 'Futuristic neon purple palette inspired by Neo-Tokyo.',
      icon: '🌆',
      cost: 50,
      category: 'theme',
      owned: true,
      value: 'violet',
    },
    {
      id: 'theme-amber',
      name: isTr ? 'Matrix Kehribar Tema' : 'Cyber Amber Gold Theme',
      description: isTr ? 'Vintage CRT monokrom sıcak amber sarısı.' : 'Warm retro CRT amber display palette.',
      icon: '✨',
      cost: 50,
      category: 'theme',
      owned: true,
      value: 'amber',
    },
    {
      id: 'sound-retro',
      name: isTr ? 'IBM Model M Daktilo Sesi' : 'IBM Model M Clicky Sound',
      description: isTr ? 'Efsanevi buckling spring mekanik anahtar akustiği.' : 'Iconic 1985 heavy buckling spring click acoustic.',
      icon: '🔊',
      cost: 35,
      category: 'sound',
      owned: true,
      value: 'clicky',
    },
    {
      id: 'sound-synth',
      name: isTr ? 'Siber Dalgaboyu Sentez Sesi' : 'Cyberwave Synth Sound',
      description: isTr ? 'Her tuş vuruşunda fütüristik müzikal mikro tonlar.' : 'Futuristic synthesizer micro-chimes on keypress.',
      icon: '🎹',
      cost: 35,
      category: 'sound',
      owned: true,
      value: 'synth',
    },
  ];
}

// ─── 6. SPONSORLU TEKNOLOJİ REKLAMLARI (TECH ADS) ───────────────────────────
export const TECH_ADS_TR: TechAd[] = [
  {
    id: 'keychron-q3',
    sponsor: 'Keychron Mechanical Keyboards',
    tagline: 'Mekanik Yazma Deneyiminin Zirvesi',
    badge: 'SPONSORLU DONANIM',
    description: 'CNC alüminyum gövde, çalışırken değiştirilebilir (hot-swappable) mekanik switchler ve akustik köpük izolasyonuyla daktilo hızını ve tuş hissiyatını %30 artır.',
    ctaText: 'Keychron Q3 Pro\'yu İncele (+1 Odak Enerjisi)',
    ctaUrl: 'https://www.keychron.com',
    rewardEnergy: 1,
    icon: '⌨️',
  },
  {
    id: 'warp-terminal',
    sponsor: 'Warp AI Terminal',
    tagline: '21. Yüzyılın Akıllı Terminali',
    badge: 'GELİŞTİRİCİ ARACI',
    description: 'Yapay zeka komut tamamlama, modern metin editörü gibi blok tabanlı komut satırı ve takım iş birliği araçlarıyla terminal hızını katla.',
    ctaText: 'Warp Terminal\'i Keşfet (+1 Odak Enerjisi)',
    ctaUrl: 'https://www.warp.dev',
    rewardEnergy: 1,
    icon: '⚡',
  },
  {
    id: 'neon-db',
    sponsor: 'Neon Serverless Postgres',
    tagline: 'Saniyeler İçinde Veritabanı Dallanması',
    badge: 'BULUT VERİTABANI',
    description: 'Git gibi dallanabilen (branching), otomatik sıfıra ölçeklenen modern serverless PostgreSQL ile Next.js ve yapay zeka projelerini anında ayağa kaldır.',
    ctaText: 'Neon DB\'de Başla (+1 Odak Enerjisi)',
    ctaUrl: 'https://neon.tech',
    rewardEnergy: 1,
    icon: '🐘',
  },
];

export const TECH_ADS_EN: TechAd[] = [
  {
    id: 'keychron-q3',
    sponsor: 'Keychron Mechanical Keyboards',
    tagline: 'The Pinnacle of Tactile Typing',
    badge: 'SPONSORED HARDWARE',
    description: 'Full CNC machined aluminum body, hot-swappable mechanical switches, and acoustic foam dampening designed to elevate your typing cadence by 30%.',
    ctaText: 'Explore Keychron Q3 Pro (+1 Focus Energy)',
    ctaUrl: 'https://www.keychron.com',
    rewardEnergy: 1,
    icon: '⌨️',
  },
  {
    id: 'warp-terminal',
    sponsor: 'Warp AI Terminal',
    tagline: 'The Intelligent Terminal for the 21st Century',
    badge: 'DEVELOPER SPONSOR',
    description: 'AI-assisted command completions, IDE-like block editing, and collaborative shell workflows built in ultra-fast Rust.',
    ctaText: 'Discover Warp Terminal (+1 Focus Energy)',
    ctaUrl: 'https://www.warp.dev',
    rewardEnergy: 1,
    icon: '⚡',
  },
  {
    id: 'neon-db',
    sponsor: 'Neon Serverless Postgres',
    tagline: 'Serverless Postgres with Instant Branching',
    badge: 'CLOUD DATABASE',
    description: 'Branch your database just like Git, scale to zero on demand, and power Next.js full-stack applications with lightning speed.',
    ctaText: 'Get Started with Neon (+1 Focus Energy)',
    ctaUrl: 'https://neon.tech',
    rewardEnergy: 1,
    icon: '🐘',
  },
];

export function getTechAds(lang: Locale): TechAd[] {
  return lang === 'tr' ? TECH_ADS_TR : TECH_ADS_EN;
}
