/**
 * TYPEFLOW — Duolingo-Grade Gamification Data Engine
 * Units, Lessons, Leagues, Quests, Achievements, and Shop Catalog.
 */

import { Unit, Lesson, LessonStage, DailyQuest, Achievement, ShopItem, LeagueMember, LeagueTier, TechAd } from './types';
import { Locale } from '@/dictionaries';

// ─── 1. DAKTILO AKADEMİSİ: 6 ÜNİTE VE DERSLERİ ────────────────────────────────
export const ACADEMY_UNITS_TR: Unit[] = [
  {
    id: 1,
    title: 'Ünite 1: Ev Sırası Temelleri (Home Row)',
    description: 'Sol ve sağ elin ana yerleşimi: A, S, D, F ve J, K, L, Ş tuşları.',
    themeColor: '#3b82f6',
    lessons: [
      {
        id: 'u1-l1',
        unitId: 1,
        title: 'İşaret Parmakları: F ve J',
        description: 'Klavyedeki kabartmalı kılavuz tuşlarına alış.',
        icon: '☝️',
        targetChars: ['f', 'j', ' '],
        words: ['f', 'j', 'ff', 'jj', 'fj', 'jf', 'fjf', 'jfj', 'fjjf', 'jffj'],
        stars: 0,
        status: 'active',
        minWpm: 15,
        minAccuracy: 90,
        xpReward: 20,
        gemReward: 10,
      },
      {
        id: 'u1-l2',
        unitId: 1,
        title: 'Sol El: A, S, D, F',
        description: 'Sol el parmaklarını ev sırasına yerleştir.',
        icon: '👈',
        targetChars: ['a', 's', 'd', 'f'],
        words: ['as', 'da', 'fa', 'sad', 'saf', 'ada', 'kasa', 'fasa', 'fas', 'safahat'],
        stars: 0,
        status: 'locked',
        minWpm: 18,
        minAccuracy: 90,
        xpReward: 25,
        gemReward: 12,
      },
      {
        id: 'u1-l3',
        unitId: 1,
        title: 'Sağ El: J, K, L, Ş',
        description: 'Sağ el parmaklarının ev sırası koordinasyonu.',
        icon: '👉',
        targetChars: ['j', 'k', 'l', 'ş'],
        words: ['ka', 'al', 'aş', 'kaş', 'şal', 'ala', 'kala', 'şaka', 'şafak', 'kasa'],
        stars: 0,
        status: 'locked',
        minWpm: 20,
        minAccuracy: 92,
        xpReward: 25,
        gemReward: 15,
      },
      {
        id: 'u1-l4',
        unitId: 1,
        title: 'Ev Sırası Sınavı: Hız ve Doğruluk',
        description: 'Tüm ev sırası harflerini kesintisiz akışla yaz.',
        icon: '🏆',
        targetChars: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ş'],
        words: ['kasa', 'şafak', 'sakal', 'fakat', 'salata', 'dalaş', 'kafa', 'fal', 'kalas'],
        stars: 0,
        status: 'locked',
        minWpm: 25,
        minAccuracy: 94,
        xpReward: 40,
        gemReward: 25,
      },
    ],
  },
  {
    id: 2,
    title: 'Ünite 2: Üst Sıra Parmak Açılımları',
    description: 'Yukarı uzanma egzersizleri: E, R, T, Y, U, I, O, P tuşları.',
    themeColor: '#10b981',
    lessons: [
      {
        id: 'u2-l1',
        unitId: 2,
        title: 'E ve R Tuşları',
        description: 'Türkçede en sık geçen sesli ve sessiz harf kombinasyonu.',
        icon: '⚡',
        targetChars: ['e', 'r'],
        words: ['er', 're', 'ere', 'ser', 'der', 'fer', 'eser', 'fare', 'kale', 'sefer'],
        stars: 0,
        status: 'locked',
        minWpm: 22,
        minAccuracy: 92,
        xpReward: 30,
        gemReward: 15,
      },
      {
        id: 'u2-l2',
        unitId: 2,
        title: 'T ve Y Tuşları',
        description: 'Merkez üst sıra uzanımı.',
        icon: '🎯',
        targetChars: ['t', 'y'],
        words: ['at', 'ay', 'yata', 'tasa', 'tava', 'taya', 'tayfa', 'telsiz', 'tarih'],
        stars: 0,
        status: 'locked',
        minWpm: 24,
        minAccuracy: 92,
        xpReward: 30,
        gemReward: 15,
      },
      {
        id: 'u2-l3',
        unitId: 2,
        title: 'U, I, O, P Tuşları',
        description: 'Sağ el üst sıra parmak esnekliği.',
        icon: '🖐️',
        targetChars: ['u', 'ı', 'o', 'p'],
        words: ['ot', 'pul', 'oluş', 'posta', 'pilot', 'toprak', 'pazar', 'patika'],
        stars: 0,
        status: 'locked',
        minWpm: 26,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 18,
      },
      {
        id: 'u2-l4',
        unitId: 2,
        title: 'Üst Sıra Ustalık Sınavı',
        description: 'Ev sırası ve üst sırayı harmanlayan akıcı kelimeler.',
        icon: '🌟',
        targetChars: ['e', 'r', 't', 'y', 'u', 'ı', 'o', 'p'],
        words: ['operatör', 'portakal', 'tasarım', 'yetenek', 'tarihi', 'telefon'],
        stars: 0,
        status: 'locked',
        minWpm: 30,
        minAccuracy: 94,
        xpReward: 50,
        gemReward: 30,
      },
    ],
  },
  {
    id: 3,
    title: 'Ünite 3: Alt Sıra ve Türkçe Karakterler',
    description: 'Aşağı uzanmalar: Z, X, C, V, B, N, M, Ö, Ç tuşları.',
    themeColor: '#8b5cf6',
    lessons: [
      {
        id: 'u3-l1',
        unitId: 3,
        title: 'C, V ve B Tuşları',
        description: 'Sol el alt sıra hareketleri.',
        icon: '⚓',
        targetChars: ['c', 'v', 'b'],
        words: ['ve', 'bu', 'can', 'var', 'bana', 'cevap', 'bavul', 'vicdan', 'bakış'],
        stars: 0,
        status: 'locked',
        minWpm: 25,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 18,
      },
      {
        id: 'u3-l2',
        unitId: 3,
        title: 'N ve M Tuşları',
        description: 'Sağ el alt sıra temelleri.',
        icon: '🌊',
        targetChars: ['n', 'm'],
        words: ['ne', 'mu', 'man', 'nam', 'anlam', 'zaman', 'insan', 'orman', 'liman'],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 92,
        xpReward: 35,
        gemReward: 18,
      },
      {
        id: 'u3-l3',
        unitId: 3,
        title: 'Ö ve Ç Tuşları',
        description: 'Türkçe klavyenin özel sağ alt karakterleri.',
        icon: '🇹🇷',
        targetChars: ['ö', 'ç'],
        words: ['ön', 'çok', 'çöl', 'öbek', 'çiçek', 'çözüm', 'örnek', 'çıkış', 'özlem'],
        stars: 0,
        status: 'locked',
        minWpm: 30,
        minAccuracy: 93,
        xpReward: 40,
        gemReward: 20,
      },
      {
        id: 'u3-l4',
        unitId: 3,
        title: 'Tüm Klavye Entegrasyon Testi',
        description: 'Üç sırayı birden kullanan kapsamlı pratik.',
        icon: '💎',
        targetChars: ['z', 'c', 'v', 'b', 'n', 'm', 'ö', 'ç'],
        words: ['müzisyen', 'çözümlemek', 'özgürlük', 'vizyoner', 'başlangıç', 'zamanlama'],
        stars: 0,
        status: 'locked',
        minWpm: 35,
        minAccuracy: 95,
        xpReward: 60,
        gemReward: 35,
      },
    ],
  },
  {
    id: 4,
    title: 'Ünite 4: Rakamlar ve Semboller',
    description: 'Sayı satırı (1-0) ve programlama sembolleri: !, @, #, $, %, &, *',
    themeColor: '#f59e0b',
    lessons: [
      {
        id: 'u4-l1',
        unitId: 4,
        title: 'Sayılar: 1, 2, 3, 4, 5',
        description: 'Sol el üst sayı satırı uzanımları.',
        icon: '🔢',
        targetChars: ['1', '2', '3', '4', '5'],
        words: ['12', '34', '51', '2026', '1453', '1024', '404', '500', '360', '1984'],
        stars: 0,
        status: 'locked',
        minWpm: 22,
        minAccuracy: 90,
        xpReward: 40,
        gemReward: 20,
      },
      {
        id: 'u4-l2',
        unitId: 4,
        title: 'Sayılar: 6, 7, 8, 9, 0',
        description: 'Sağ el üst sayı satırı uzanımları.',
        icon: '🔢',
        targetChars: ['6', '7', '8', '9', '0'],
        words: ['78', '90', '67', '2080', '1999', '8080', '999', '700', '888'],
        stars: 0,
        status: 'locked',
        minWpm: 22,
        minAccuracy: 90,
        xpReward: 40,
        gemReward: 20,
      },
      {
        id: 'u4-l3',
        unitId: 4,
        title: 'Parantezler ve Eşitlik: (), [], {}',
        description: 'Kod yazarken en çok kullanılan blok işaretleri.',
        icon: '🧩',
        targetChars: ['(', ')', '{', '}', '[', ']'],
        words: ['(test)', '{id:1}', '[0]', 'fn()', '{status:ok}', '[items]', 'calc(10)'],
        stars: 0,
        status: 'locked',
        minWpm: 25,
        minAccuracy: 92,
        xpReward: 45,
        gemReward: 25,
      },
      {
        id: 'u4-l4',
        unitId: 4,
        title: 'Sembol Karışımı Sınavı',
        description: 'Harf, rakam ve sembollerin karma akışı.',
        icon: '🔥',
        targetChars: ['!', '?', '-', '_', '=', '+'],
        words: ['count=10', 'id_key', 'total+sum', 'val!=null', 'api-v2', 'is_valid?'],
        stars: 0,
        status: 'locked',
        minWpm: 28,
        minAccuracy: 93,
        xpReward: 65,
        gemReward: 40,
      },
    ],
  },
  {
    id: 5,
    title: 'Ünite 5: Hızlı ve Akıcı Cümleler',
    description: 'Gerçek dünya metinleri, edebi cümleler ve ritmik hız antrenmanı.',
    themeColor: '#ec4899',
    lessons: [
      {
        id: 'u5-l1',
        unitId: 5,
        title: 'Kısa ve Tempolu Cümleler',
        description: 'Hafıza ve parmak koordinasyonunu birleştir.',
        icon: '✍️',
        targetChars: ['all'],
        words: ['Zaman', 'hızla', 'akıp', 'gidiyor.', 'Bugün', 'yeni', 'bir', 'rekor', 'kır.'],
        stars: 0,
        status: 'locked',
        minWpm: 35,
        minAccuracy: 94,
        xpReward: 50,
        gemReward: 25,
      },
      {
        id: 'u5-l2',
        unitId: 5,
        title: 'Düşünce Hızında Yazım',
        description: 'Harfleri değil kelimeleri blok olarak algıla.',
        icon: '🧠',
        targetChars: ['all'],
        words: ['Klavye', 'parmakların', 'doğal', 'bir', 'uzantısı', 'haline', 'gelmelidir.'],
        stars: 0,
        status: 'locked',
        minWpm: 45,
        minAccuracy: 95,
        xpReward: 60,
        gemReward: 30,
      },
      {
        id: 'u5-l3',
        unitId: 5,
        title: 'Yüksek Hız Koridoru (60+ WPM)',
        description: 'Işık hızında klavye ustalığı.',
        icon: '🚀',
        targetChars: ['all'],
        words: ['Kesintisiz', 'odaklanma', 've', 'kusursuz', 'doğruluk', 'başarının', 'anahtarıdır.'],
        stars: 0,
        status: 'locked',
        minWpm: 55,
        minAccuracy: 96,
        xpReward: 75,
        gemReward: 40,
      },
      {
        id: 'u5-l4',
        unitId: 5,
        title: 'Hız Efsanesi Finali',
        description: 'Gelişmiş akıcılık ve refleks doğrulaması.',
        icon: '👑',
        targetChars: ['all'],
        words: ['Saniyede', 'onlarca', 'harf', 'üreten', 'zihin,', 'dijital', 'çağın', 'mimarıdır.'],
        stars: 0,
        status: 'locked',
        minWpm: 65,
        minAccuracy: 96,
        xpReward: 100,
        gemReward: 50,
      },
    ],
  },
  {
    id: 6,
    title: 'Ünite 6: Geliştirici & Terminal Ustası',
    description: 'PowerShell, Bash, Git ve TypeScript gerçek kod komutları.',
    themeColor: '#06b6d4',
    lessons: [
      {
        id: 'u6-l1',
        unitId: 6,
        title: 'Git & Terminal Temelleri',
        description: 'Her yazılımcının el refleksi olması gereken komutlar.',
        icon: '💻',
        targetChars: ['all'],
        words: ['git', 'commit', '-m', '"feat:"', 'git', 'push', 'origin', 'main', 'npm', 'run', 'dev'],
        stars: 0,
        status: 'locked',
        minWpm: 35,
        minAccuracy: 95,
        xpReward: 60,
        gemReward: 30,
      },
      {
        id: 'u6-l2',
        unitId: 6,
        title: 'PowerShell & Sistem Betikleri',
        description: 'Windows terminali ve sunucu yönetimi parametreleri.',
        icon: '⚙️',
        targetChars: ['all'],
        words: ['Get-Process', '|', 'Where-Object', 'CPU', '-gt', '10', 'Stop-Service', '-Force'],
        stars: 0,
        status: 'locked',
        minWpm: 38,
        minAccuracy: 95,
        xpReward: 70,
        gemReward: 35,
      },
      {
        id: 'u6-l3',
        unitId: 6,
        title: 'Modern TypeScript Sentaksı',
        description: 'Generics, arrow functions ve async/await yapıları.',
        icon: '💠',
        targetChars: ['all'],
        words: ['const', 'fetchData', '=', 'async', '<T>():', 'Promise<T>', '=>', '{', 'return', 'res;', '}'],
        stars: 0,
        status: 'locked',
        minWpm: 42,
        minAccuracy: 96,
        xpReward: 85,
        gemReward: 45,
      },
      {
        id: 'u6-l4',
        unitId: 6,
        title: 'Akademi Mezuniyet Projesi: Full-Stack Hacker',
        description: 'Tüm klavyeyi kapsayan nihai geliştirici hız testi.',
        icon: '🎓',
        targetChars: ['all'],
        words: ['export', 'default', 'async', 'function', 'handler(req,', 'res)', '{', 'await', 'db.connect();', '}'],
        stars: 0,
        status: 'locked',
        minWpm: 50,
        minAccuracy: 97,
        xpReward: 150,
        gemReward: 100,
      },
    ],
  },
  {
    id: 7,
    title: 'Ünite 7: Türk Edebiyatı ve Usta Yazarlar',
    description: 'Sabahattin Ali, Nazım Hikmet, Oğuz Atay ve Atatürk\'ün ölümsüz eserleriyle edebi hız egzersizi.',
    themeColor: '#f97316',
    lessons: [
      {
        id: 'u7-l1',
        unitId: 7,
        title: 'Sabahattin Ali — Kürk Mantolu Madonna',
        description: 'Duygusal derinlik ve edebi anlatı akışı.',
        icon: '📖',
        targetChars: ['all'],
        words: ['İçimde', 'hiçbir', 'şeye', 'karşı', 'bir', 'istek,', 'bir', 'heves', 'kalmamıştı.', 'Yalnızdım.'],
        stars: 0,
        status: 'locked',
        minWpm: 38,
        minAccuracy: 95,
        xpReward: 70,
        gemReward: 35,
      },
      {
        id: 'u7-l2',
        unitId: 7,
        title: 'Nazım Hikmet — Umut Şiiri',
        description: 'Ritmik, coşkulu ve akıcı şiirsel mısralar.',
        icon: '🕊️',
        targetChars: ['all'],
        words: ['Güzel', 'günler', 'göreceğiz', 'çocuklar,', 'güneşli', 'günler', 'göreceğiz.', 'İnanın.'],
        stars: 0,
        status: 'locked',
        minWpm: 40,
        minAccuracy: 95,
        xpReward: 75,
        gemReward: 40,
      },
      {
        id: 'u7-l3',
        unitId: 7,
        title: 'Oğuz Atay — Tutunamayanlar',
        description: 'Zihinsel monolog ve yoğun kelime dizilimi.',
        icon: '🎭',
        targetChars: ['all'],
        words: ['Kelimeler,', 'albayım,', 'bazı', 'anlamlara', 'gelmiyor.', 'İnsan', 'bazen', 'susmalı.'],
        stars: 0,
        status: 'locked',
        minWpm: 44,
        minAccuracy: 96,
        xpReward: 85,
        gemReward: 45,
      },
      {
        id: 'u7-l4',
        unitId: 7,
        title: 'Mustafa Kemal Atatürk — Gençliğe Hitabe',
        description: 'Tarihi hitabet gücü ve yüksek odaklanma testi.',
        icon: '🇹🇷',
        targetChars: ['all'],
        words: ['Ey', 'Türk', 'gençliği!', 'Birinci', 'vazifen,', 'Türk', 'istiklâlini', 'ilelebet', 'muhafaza', 'etmektir.'],
        stars: 0,
        status: 'locked',
        minWpm: 48,
        minAccuracy: 97,
        xpReward: 120,
        gemReward: 60,
      },
    ],
  },
  {
    id: 8,
    title: 'Ünite 8: Çoklu Dil & Algoritma (Python, Rust, React, SQL)',
    description: 'Modern yazılım dünyasında en çok kullanılan dillerin sentaks ve blokları.',
    themeColor: '#38bdf8',
    lessons: [
      {
        id: 'u8-l1',
        unitId: 8,
        title: 'Python & Veri Bilimi',
        description: 'List comprehensions ve fonksiyonel Python.',
        icon: '🐍',
        targetChars: ['all'],
        words: ['import', 'numpy', 'as', 'np;', 'data', '=', '[x**2', 'for', 'x', 'in', 'range(10)]'],
        stars: 0,
        status: 'locked',
        minWpm: 36,
        minAccuracy: 95,
        xpReward: 80,
        gemReward: 40,
      },
      {
        id: 'u8-l2',
        unitId: 8,
        title: 'React 19 Hooks & State',
        description: 'Modern front-end bileşen yapıları.',
        icon: '⚛️',
        targetChars: ['all'],
        words: ['const', '[state,', 'setState]', '=', 'useState(false);', 'useEffect(()', '=>', '{}', ',[]);'],
        stars: 0,
        status: 'locked',
        minWpm: 38,
        minAccuracy: 95,
        xpReward: 85,
        gemReward: 45,
      },
      {
        id: 'u8-l3',
        unitId: 8,
        title: 'Rust Sistem & Bellek Güvenliği',
        description: 'Rust pattern matching ve lifetime sentaksı.',
        icon: '🦀',
        targetChars: ['all'],
        words: ['fn', 'process<T>(val:', 'Option<T>)', '->', 'Result<T,', 'Error>', '{', 'val.ok_or(Err)', '}'],
        stars: 0,
        status: 'locked',
        minWpm: 40,
        minAccuracy: 96,
        xpReward: 90,
        gemReward: 50,
      },
      {
        id: 'u8-l4',
        unitId: 8,
        title: 'SQL Veritabanı & Karmaşık Sorgular',
        description: 'JOIN, GROUP BY ve WHERE mantıksal sorguları.',
        icon: '🗄️',
        targetChars: ['all'],
        words: ['SELECT', 'u.id,', 'COUNT(o.id)', 'FROM', 'users', 'u', 'JOIN', 'orders', 'o', 'GROUP', 'BY', 'u.id;'],
        stars: 0,
        status: 'locked',
        minWpm: 42,
        minAccuracy: 96,
        xpReward: 100,
        gemReward: 55,
      },
    ],
  },
  {
    id: 9,
    title: 'Ünite 9: Finans, Rakamlar ve Hız Koridoru',
    description: 'Para birimleri, tarihler, sözleşmeler ve Daktilo Grand Master unvanı.',
    themeColor: '#eab308',
    lessons: [
      {
        id: 'u9-l1',
        unitId: 9,
        title: 'Para Birimleri ve Döviz Kurları',
        description: '₺, $, €, % ve ondalık basamaklar.',
        icon: '💰',
        targetChars: ['all'],
        words: ['1.250,50₺', '$450.00', '€2.800', '%18.5', 'KDV', 'USD/TRY', 'paritesi', 'güncellendi.'],
        stars: 0,
        status: 'locked',
        minWpm: 35,
        minAccuracy: 94,
        xpReward: 85,
        gemReward: 45,
      },
      {
        id: 'u9-l2',
        unitId: 9,
        title: 'Tarihler ve Zaman Damgaları',
        description: 'ISO 8601, saatler ve takvim akışı.',
        icon: '📅',
        targetChars: ['all'],
        words: ['2026-09-11', '16:30:00', '1923-10-29', '09:05', 'UTC+03:00', 'zaman', 'damgası'],
        stars: 0,
        status: 'locked',
        minWpm: 38,
        minAccuracy: 95,
        xpReward: 90,
        gemReward: 50,
      },
      {
        id: 'u9-l3',
        unitId: 9,
        title: 'Hukuk ve Sözleşme Dili',
        description: 'Resmi metinler ve terimler.',
        icon: '⚖️',
        targetChars: ['all'],
        words: ['Taraflar', 'işbu', 'sözleşme', 'hükümlerini', 'gayrikabili', 'rücu', 'kabul', 've', 'taahhüt', 'eder.'],
        stars: 0,
        status: 'locked',
        minWpm: 44,
        minAccuracy: 96,
        xpReward: 110,
        gemReward: 60,
      },
      {
        id: 'u9-l4',
        unitId: 9,
        title: 'Daktilo Grand Master: Nihai Sınav',
        description: 'Tüm klavye, edebi derinlik ve kodlama bilgini birleştiren zirve testi.',
        icon: '👑',
        targetChars: ['all'],
        words: ['Klavye', 'artık', 'parmaklarının', 'uzantısı;', 'düşüncelerin', 'ışık', 'hızında', 'dijital', 'dünyaya', 'akıyor.'],
        stars: 0,
        status: 'locked',
        minWpm: 60,
        minAccuracy: 98,
        xpReward: 250,
        gemReward: 150,
      },
    ],
  },
];

export const ACADEMY_UNITS_EN: Unit[] = [
  {
    id: 1,
    title: 'Unit 1: Home Row Fundamentals',
    description: 'Master anchor keys: A, S, D, F and J, K, L, ; keys.',
    themeColor: '#3b82f6',
    lessons: [
      {
        id: 'u1-l1',
        unitId: 1,
        title: 'Index Fingers: F and J',
        description: 'Locate the tactile bumps on F and J.',
        icon: '☝️',
        targetChars: ['f', 'j', ' '],
        words: ['f', 'j', 'ff', 'jj', 'fj', 'jf', 'fjf', 'jfj', 'fjjf', 'jffj'],
        stars: 0,
        status: 'active',
        minWpm: 15,
        minAccuracy: 90,
        xpReward: 20,
        gemReward: 10,
      },
      {
        id: 'u1-l2',
        unitId: 1,
        title: 'Left Hand: A, S, D, F',
        description: 'Position left fingers on home keys.',
        icon: '👈',
        targetChars: ['a', 's', 'd', 'f'],
        words: ['as', 'sad', 'fad', 'dad', 'falls', 'salsa', 'flask', 'salad'],
        stars: 0,
        status: 'locked',
        minWpm: 18,
        minAccuracy: 90,
        xpReward: 25,
        gemReward: 12,
      },
      {
        id: 'u1-l3',
        unitId: 1,
        title: 'Right Hand: J, K, L, ;',
        description: 'Right hand home row coordination.',
        icon: '👉',
        targetChars: ['j', 'k', 'l'],
        words: ['ask', 'all', 'fall', 'lad', 'glad', 'flask', 'alas', 'kala'],
        stars: 0,
        status: 'locked',
        minWpm: 20,
        minAccuracy: 92,
        xpReward: 25,
        gemReward: 15,
      },
      {
        id: 'u1-l4',
        unitId: 1,
        title: 'Home Row Checkpoint',
        description: 'Full home row fluid stream.',
        icon: '🏆',
        targetChars: ['a', 's', 'd', 'f', 'j', 'k', 'l'],
        words: ['flash', 'salad', 'flask', 'falls', 'glass', 'alfalfa', 'dallas'],
        stars: 0,
        status: 'locked',
        minWpm: 25,
        minAccuracy: 94,
        xpReward: 40,
        gemReward: 25,
      },
    ],
  },
];

export function ensureLessonStages(lesson: Lesson, lang: Locale = 'tr'): LessonStage[] {
  if (lesson.stages && lesson.stages.length >= 3) {
    return lesson.stages;
  }
  const isTr = lang === 'tr';
  const chars = lesson.targetChars.filter(c => c !== 'all' && c !== ' ');
  const charA = chars[0] || (isTr ? 'a' : 'e');
  const charB = chars[1] || (isTr ? 's' : 't');
  const charC = chars[2] || (isTr ? 'd' : 'a');

  // Stage 1: Kas Hafızası & Parmak Yerleşimi (Rhythmic Muscle Memory Drills)
  const drillWords = chars.length >= 2
    ? [charA, charB, `${charA}${charA}`, `${charB}${charB}`, `${charA}${charB}`, `${charB}${charA}`, `${charA}${charB}${charA}`, `${charB}${charA}${charB}`, `${charA}${charA}${charB}${charB}`, `${charB}${charA}${charB}${charA}`]
    : lesson.words.slice(0, 6).map(w => w.toLowerCase());

  // Stage 2: Hedef Kelime İnşası & Hız (Core Vocabulary Building)
  const vocabWords = lesson.words.length >= 8 ? lesson.words : [...lesson.words, ...lesson.words];

  // Stage 3: Akıcı Cümleler & Ustalık Sınavı (Sentences & Star Mastery Flow)
  const sentenceFlow = isTr
    ? [
        lesson.title + ' ile klavyede kusursuz ritmi ve akışı yakala.',
        'Parmaklarını ev sırasından ayırmadan hedefe odaklan ve hızlan.',
        'Hatasız vuruş serileriyle ustalığını kanıtla.'
      ].join(' ').split(' ')
    : [
        'Master ' + lesson.title + ' with smooth and balanced cadence.',
        'Keep fingers centered on the home row and accelerate steadily.',
        'Prove your mastery with zero hesitation and clean accuracy.'
      ].join(' ').split(' ');

  return [
    {
      stageIndex: 1,
      title: isTr ? 'Aşama 1: Kas Hafızası & Parmak Yerleşimi' : 'Stage 1: Muscle Memory Drills',
      description: isTr ? 'Parmak konumlandırma ve ritmik tuş vuruş tekrarları.' : 'Key finger positioning and rhythmic key repetition.',
      type: 'drill',
      targetChars: lesson.targetChars,
      words: drillWords,
      minWpm: Math.max(12, Math.round(lesson.minWpm * 0.7)),
      minAccuracy: Math.max(88, lesson.minAccuracy - 2),
    },
    {
      stageIndex: 2,
      title: isTr ? 'Aşama 2: Kelime İnşası & Hız' : 'Stage 2: Core Vocabulary & Speed',
      description: isTr ? 'Öğrenilen harflerle hedef kelime dağarcığını pekiştir.' : 'Reinforce vocabulary with target key combinations.',
      type: 'words',
      targetChars: lesson.targetChars,
      words: vocabWords,
      minWpm: lesson.minWpm,
      minAccuracy: lesson.minAccuracy,
    },
    {
      stageIndex: 3,
      title: isTr ? 'Aşama 3: Akıcı Cümleler & Ustalık Sınavı' : 'Stage 3: Flow Sentences & Mastery Test',
      description: isTr ? 'Noktalama, akışkanlık ve yıldız kazanma sınavı.' : 'Punctuation, natural cadence, and star mastery test.',
      type: 'sentences',
      targetChars: lesson.targetChars,
      words: sentenceFlow,
      minWpm: Math.round(lesson.minWpm * 1.1),
      minAccuracy: Math.min(98, lesson.minAccuracy + 2),
    },
  ];
}

export function getUnitsForLang(lang: Locale): Unit[] {
  const baseUnits = lang === 'tr' ? ACADEMY_UNITS_TR : ACADEMY_UNITS_EN;
  // Ensure every lesson has the 3-stage mastery curriculum
  return baseUnits.map(unit => ({
    ...unit,
    lessons: unit.lessons.map(lesson => ({
      ...lesson,
      stages: ensureLessonStages(lesson, lang),
    })),
  }));
}

// ─── 2. DUOLINGO LİGLERİ (LEAGUES) ───────────────────────────────────────────
export const LEAGUE_TIERS: { id: LeagueTier; nameTr: string; nameEn: string; icon: string; minXp: number }[] = [
  { id: 'bronze', nameTr: 'Membran Çırakları', nameEn: 'Membrane Apprentices', icon: '🥉', minXp: 0 },
  { id: 'silver', nameTr: 'Mekanik Tuş Birliği', nameEn: 'Mechanical Switch Guild', icon: '🥈', minXp: 150 },
  { id: 'gold', nameTr: 'Kızıl Switch Locası', nameEn: 'Red Linear Swarm', icon: '🥇', minXp: 350 },
  { id: 'sapphire', nameTr: 'Kapasitif Usta Topluluğu', nameEn: 'Topre Capacitive Order', icon: '💎', minXp: 600 },
  { id: 'diamond', nameTr: 'Daktilo Kozmosu // Optik Zirve', nameEn: 'Quantum Optical Overlord', icon: '👑', minXp: 1000 },
];

export const MOCK_LEAGUE_MEMBERS: Record<LeagueTier, LeagueMember[]> = {
  bronze: [
    { id: 'b1', username: 'cyber_phoenix', avatar: '🔥', weeklyXp: 280, rank: 1 },
    { id: 'b2', username: 'neo_coder', avatar: '⚡', weeklyXp: 245, rank: 2 },
    { id: 'b3', username: 'ghost_typist', avatar: '👻', weeklyXp: 210, rank: 3 },
    { id: 'b4', username: 'terminal_root', avatar: '🤖', weeklyXp: 160, rank: 4 },
    { id: 'b5', username: 'speedy_fox', avatar: '🦊', weeklyXp: 130, rank: 5 },
    { id: 'b6', username: 'retro_coder', avatar: '👾', weeklyXp: 95, rank: 6 },
    { id: 'b7', username: 'quantum_leap', avatar: '🌐', weeklyXp: 60, rank: 7 },
  ],
  silver: [
    { id: 's1', username: 'vortex_pulse', avatar: '🌀', weeklyXp: 490, rank: 1 },
    { id: 's2', username: 'neon_rider', avatar: '🏍️', weeklyXp: 430, rank: 2 },
    { id: 's3', username: 'matrix_hacker', avatar: '🕶️', weeklyXp: 380, rank: 3 },
    { id: 's4', username: 'syntax_witch', avatar: '🔮', weeklyXp: 310, rank: 4 },
    { id: 's5', username: 'pixel_monk', avatar: '🧘', weeklyXp: 260, rank: 5 },
  ],
  gold: [
    { id: 'g1', username: 'hyper_velocity', avatar: '🚀', weeklyXp: 720, rank: 1 },
    { id: 'g2', username: 'chronos_time', avatar: '⏳', weeklyXp: 650, rank: 2 },
    { id: 'g3', username: 'solaris_prime', avatar: '☀️', weeklyXp: 590, rank: 3 },
    { id: 'g4', username: 'apex_predator', avatar: '🦅', weeklyXp: 510, rank: 4 },
  ],
  sapphire: [
    { id: 'sp1', username: 'celestial_zen', avatar: '✨', weeklyXp: 940, rank: 1 },
    { id: 'sp2', username: 'frost_byte', avatar: '❄️', weeklyXp: 880, rank: 2 },
    { id: 'sp3', username: 'deep_ocean', avatar: '🌊', weeklyXp: 820, rank: 3 },
  ],
  diamond: [
    { id: 'd1', username: 'omnipresent_god', avatar: '👑', weeklyXp: 1450, rank: 1 },
    { id: 'd2', username: 'speed_of_light', avatar: '⚡', weeklyXp: 1320, rank: 2 },
    { id: 'd3', username: 'singularity_ai', avatar: '🌌', weeklyXp: 1210, rank: 3 },
  ],
};

// ─── 3. GÜNLÜK GÖREVLER (DAILY QUESTS) ───────────────────────────────────────
export function getDailyQuests(lang: Locale, userXpToday: number, testsToday: number, lessonsToday: number): DailyQuest[] {
  const isTr = lang === 'tr';
  return [
    {
      id: 'quest-xp',
      title: isTr ? 'Günlük XP Avcısı' : 'Daily XP Hunter',
      description: isTr ? 'Bugün 40 XP topla' : 'Earn 40 XP today',
      icon: '⚡',
      current: Math.min(userXpToday, 40),
      target: 40,
      xpReward: 20,
      gemReward: 15,
      isCompleted: userXpToday >= 40,
      isClaimed: false,
    },
    {
      id: 'quest-tests',
      title: isTr ? 'Klavye Isınması' : 'Keyboard Warmup',
      description: isTr ? '2 test veya ders tamamla' : 'Complete 2 tests or lessons',
      icon: '⌨️',
      current: Math.min(testsToday, 2),
      target: 2,
      xpReward: 25,
      gemReward: 20,
      isCompleted: testsToday >= 2,
      isClaimed: false,
    },
    {
      id: 'quest-lesson',
      title: isTr ? 'Akademi İlerlemesi' : 'Academy Progress',
      description: isTr ? 'Daktilo Akademisinde 1 ders tamamla' : 'Complete 1 academy lesson',
      icon: '🗺️',
      current: Math.min(lessonsToday, 1),
      target: 1,
      xpReward: 30,
      gemReward: 25,
      isCompleted: lessonsToday >= 1,
      isClaimed: false,
    },
  ];
}

// ─── 4. BAŞARIMLAR (ACHIEVEMENTS) ────────────────────────────────────────────
export function getAchievementsList(lang: Locale): Achievement[] {
  const isTr = lang === 'tr';
  return [
    {
      id: 'first-step',
      title: isTr ? 'İlk Adım' : 'First Step',
      description: isTr ? 'İlk yazım testini veya dersini tamamla.' : 'Complete your very first test or lesson.',
      icon: '🌱',
      current: 0,
      target: 1,
      isUnlocked: false,
      rewardGems: 20,
    },
    {
      id: 'sniper-acc',
      title: isTr ? 'Keskin Nişancı' : 'Sniper Accuracy',
      description: isTr ? '%98 veya üzeri doğrulukla bir test bitir.' : 'Finish a test with 98%+ accuracy.',
      icon: '🎯',
      current: 0,
      target: 1,
      isUnlocked: false,
      rewardGems: 35,
    },
    {
      id: 'speed-demon',
      title: isTr ? 'Hız Canavarı (60 WPM)' : 'Speed Demon (60 WPM)',
      description: isTr ? '60 WPM hız barajını aş.' : 'Break the 60 WPM speed barrier.',
      icon: '🏎️',
      current: 0,
      target: 60,
      isUnlocked: false,
      rewardGems: 50,
    },
    {
      id: 'light-speed',
      title: isTr ? 'Işık Hızı (100 WPM)' : 'Speed of Light (100 WPM)',
      description: isTr ? '100 WPM hız barajını devir.' : 'Achieve 100+ WPM in any mode.',
      icon: '⚡',
      current: 0,
      target: 100,
      isUnlocked: false,
      rewardGems: 150,
    },
    {
      id: 'fire-keeper',
      title: isTr ? 'Ateş Muhafızı' : 'Fire Keeper',
      description: isTr ? '3 günlük seri yakala (Daily Streak).' : 'Maintain a 3-day typing streak.',
      icon: '🔥',
      current: 1,
      target: 3,
      isUnlocked: false,
      rewardGems: 60,
    },
    {
      id: 'code-ninja',
      title: isTr ? 'Kod Cambazı' : 'Code Ninja',
      description: isTr ? 'Kod & CLI modunda 3 oturum tamamla.' : 'Complete 3 tests in Code & CLI mode.',
      icon: '🥷',
      current: 0,
      target: 3,
      isUnlocked: false,
      rewardGems: 45,
    },
    {
      id: 'gem-hoarder',
      title: isTr ? 'Elmas Zengini' : 'Gem Hoarder',
      description: isTr ? 'Toplam 200 Elmas topla.' : 'Collect 200 total gems.',
      icon: '💎',
      current: 0,
      target: 200,
      isUnlocked: false,
      rewardGems: 80,
    },
    {
      id: 'night-owl',
      title: isTr ? 'Gece Kuşu' : 'Night Owl',
      description: isTr ? 'Gece 22:00 ile 05:00 arasında pratik yap.' : 'Practice between 10 PM and 5 AM.',
      icon: '🦉',
      current: 0,
      target: 1,
      isUnlocked: false,
      rewardGems: 30,
    },
  ];
}

// ─── 5. DUOLINGO MAĞAZASI (SHOP CATALOG) ─────────────────────────────────────
export function getShopCatalog(lang: Locale): ShopItem[] {
  const isTr = lang === 'tr';
  return [
    {
      id: 'super-typeflow',
      name: isTr ? '👑 Super TypeFlow (Pro SaaS Planı)' : '👑 Super TypeFlow (Pro Plan)',
      description: isTr
        ? 'Sınırsız Odak Enerjisi (♾️), Sıfır Reklam (🚫), Tüm Temalar & Mekanik Sesler Açık, 2X Hızlı XP ve Altın Profil Rozeti!'
        : 'Unlimited Focus Energy (♾️), Zero Ads (🚫), All Themes & Sounds Unlocked, 2X XP Boost and Golden Profile Glow!',
      icon: '👑',
      cost: 400,
      category: 'utility',
      owned: false,
    },
    {
      id: 'refill-energy',
      name: isTr ? '🔋 Odak Bataryasını Şarj Et (5/5)' : '🔋 Recharge Focus Battery (5/5)',
      description: isTr ? 'Akademi dersleri ve pratikler için bataryanı maksimum kapasiteye doldurur.' : 'Instantly restores full 5/5 focus battery for academy lessons.',
      icon: '🔋',
      cost: 60,
      category: 'utility',
      owned: false,
    },
    {
      id: 'streak-freeze',
      name: isTr ? 'Seri Dondurucu (Streak Freeze)' : 'Streak Freeze',
      description: isTr ? 'Bir gün yazmayı kaçırsan bile günlük serin korunur.' : 'Preserves your streak if you miss a day of practice.',
      icon: '🧊',
      cost: 150,
      category: 'utility',
      owned: false,
    },
    {
      id: 'theme-violet',
      name: isTr ? 'Tokyo Neon Mor Tema' : 'Tokyo Neon Violet Theme',
      description: isTr ? 'Siberpunk Tokyo gecelerinden ilham alan mor neon tema.' : 'Futuristic neon purple palette inspired by Neo-Tokyo.',
      icon: '🌆',
      cost: 200,
      category: 'theme',
      owned: true, // Default available
      value: 'violet',
    },
    {
      id: 'theme-amber',
      name: isTr ? 'Matrix Kehribar Tema' : 'Cyber Amber Gold Theme',
      description: isTr ? 'Vintage CRT monokrom sıcak amber sarısı.' : 'Warm retro CRT amber display palette.',
      icon: '✨',
      cost: 180,
      category: 'theme',
      owned: true,
      value: 'amber',
    },
    {
      id: 'sound-retro',
      name: isTr ? 'IBM Model M Daktilo Sesi' : 'IBM Model M Clicky Sound',
      description: isTr ? 'Efsanevi buckling spring mekanik anahtar akustiği.' : 'Iconic 1985 heavy buckling spring click acoustic.',
      icon: '🔊',
      cost: 120,
      category: 'sound',
      owned: true,
      value: 'clicky',
    },
    {
      id: 'sound-synth',
      name: isTr ? 'Siber Dalgaboyu Sentez Sesi' : 'Cyberwave Synth Sound',
      description: isTr ? 'Her tuş vuruşunda fütüristik müzikal mikro tonlar.' : 'Futuristic synthesizer micro-chimes on keypress.',
      icon: '🎹',
      cost: 140,
      category: 'sound',
      owned: true,
      value: 'synth',
    },
  ];
}

// ─── 6. SPONSORLU TEKNOLOJİ REKLAMLARI (TECH ADS) ───────────────────────────
export const TECH_ADS_TR: TechAd[] = [
  {
    id: 'keychron-q3',
    sponsor: 'Keychron Mechanical Keyboards',
    tagline: 'Mekanik Yazma Deneyiminin Zirvesi',
    badge: 'SPONSORLU DONANIM',
    description: 'CNC alüminyum gövde, çalışırken değiştirilebilir (hot-swappable) mekanik switchler ve akustik köpük izolasyonuyla daktilo hızını ve tuş hissiyatını %30 artır.',
    ctaText: 'Keychron Q3 Pro\'yu İncele (+1 Odak Enerjisi)',
    ctaUrl: 'https://www.keychron.com',
    rewardEnergy: 1,
    icon: '⌨️',
  },
  {
    id: 'warp-terminal',
    sponsor: 'Warp AI Terminal',
    tagline: '21. Yüzyılın Akıllı Terminali',
    badge: 'GELİŞTİRİCİ ARACI',
    description: 'Yapay zeka komut tamamlama, modern metin editörü gibi blok tabanlı komut satırı ve takım iş birliği araçlarıyla terminal hızını katla.',
    ctaText: 'Warp Terminal\'i Keşfet (+1 Odak Enerjisi)',
    ctaUrl: 'https://www.warp.dev',
    rewardEnergy: 1,
    icon: '⚡',
  },
  {
    id: 'neon-db',
    sponsor: 'Neon Serverless Postgres',
    tagline: 'Saniyeler İçinde Veritabanı Dallanması',
    badge: 'BULUT VERİTABANI',
    description: 'Git gibi dallanabilen (branching), otomatik sıfıra ölçeklenen modern serverless PostgreSQL ile Next.js ve yapay zeka projelerini anında ayağa kaldır.',
    ctaText: 'Neon DB\'de Başla (+1 Odak Enerjisi)',
    ctaUrl: 'https://neon.tech',
    rewardEnergy: 1,
    icon: '🐘',
  },
];

export const TECH_ADS_EN: TechAd[] = [
  {
    id: 'keychron-q3',
    sponsor: 'Keychron Mechanical Keyboards',
    tagline: 'The Pinnacle of Tactile Typing',
    badge: 'SPONSORED HARDWARE',
    description: 'Full CNC machined aluminum body, hot-swappable mechanical switches, and acoustic foam dampening designed to elevate your typing cadence by 30%.',
    ctaText: 'Explore Keychron Q3 Pro (+1 Focus Energy)',
    ctaUrl: 'https://www.keychron.com',
    rewardEnergy: 1,
    icon: '⌨️',
  },
  {
    id: 'warp-terminal',
    sponsor: 'Warp AI Terminal',
    tagline: 'The Intelligent Terminal for the 21st Century',
    badge: 'DEVELOPER SPONSOR',
    description: 'AI-assisted command completions, IDE-like block editing, and collaborative shell workflows built in ultra-fast Rust.',
    ctaText: 'Discover Warp Terminal (+1 Focus Energy)',
    ctaUrl: 'https://www.warp.dev',
    rewardEnergy: 1,
    icon: '⚡',
  },
  {
    id: 'neon-db',
    sponsor: 'Neon Serverless Postgres',
    tagline: 'Serverless Postgres with Instant Branching',
    badge: 'CLOUD DATABASE',
    description: 'Branch your database just like Git, scale to zero on demand, and power Next.js full-stack applications with lightning speed.',
    ctaText: 'Get Started with Neon (+1 Focus Energy)',
    ctaUrl: 'https://neon.tech',
    rewardEnergy: 1,
    icon: '🐘',
  },
];

export function getTechAds(lang: Locale): TechAd[] {
  return lang === 'tr' ? TECH_ADS_TR : TECH_ADS_EN;
}
